screen drawing
gives
	layer
		drawing sprite
			shape rectangle
				size
					width 13
					height 17
				color
					red given fragment position top
					green given fragment position left
					blue 12
		position
			top 12
			left 14
	layer drawing
		sprite shape image curly
		position
			top 12
			left 13

circle
	center
		x 10
		y 12
	radius 14
apply
	given circle radius number
	plus given circle radius number
