package leo13

val caseWord = word("case")
val choiceWord = word("choice")
val defineWord = word("define")
val eitherWord = word("either")
val expectedWord = word("expected")
val givenWord = word("given")
val givesWord = word("gives")
val hasWord = word("has")
val metaWord = word("meta")
val noneWord = word("none")
val oneWord = word("one")
val patternWord = word("pattern")
val poisonWord = word("poison")
val sentenceWord = word("sentence")
val switchWord = word("switch")
val zeroWord = word("zero")
