package leo13

val caseWord = word("case")
val choiceWord = word("choice")
val defineWord = word("define")
val eitherWord = word("either")
val expectedWord = word("expected")
val givenWord = word("given")
val givesWord = word("gives")
val hasWord = word("has")
val lineWord = word("line")
val metaWord = word("meta")
val noneWord = word("none")
val oneWord = word("one")
val patternWord = word("pattern")
val pointWord = word("point")
val poisonWord = word("poison")
val sentenceWord = word("sentence")
val switchWord = word("switch")
val xWord = word("x")
val yWord = word("y")
val zWord = word("z")
val zeroWord = word("zero")
