package dsl

fun and(vararg ts: Any?) = listOf("and", *ts)
fun any(vararg ts: Any?) = listOf("any", *ts)
fun _as(vararg ts: Any?) = listOf("as", *ts)
fun bit(vararg ts: Any?) = listOf("bit", *ts)
fun boolean(vararg ts: Any?) = listOf("boolean", *ts)
fun define(vararg ts: Any?) = listOf("define", *ts)
fun either(vararg ts: Any?) = listOf("either", *ts)
fun gives(vararg ts: Any?) = listOf("gives", *ts)
fun _is(vararg ts: Any?) = listOf("is", *ts)
fun it(vararg ts: Any?) = listOf("it", *ts)
fun language(vararg ts: Any?) = listOf("language", *ts)
fun leo(vararg ts: Any?) = listOf("leo", *ts)
fun of(vararg ts: Any?) = listOf("of", *ts)
fun one(vararg ts: Any?) = listOf("one", *ts)
fun or(vararg ts: Any?) = listOf("or", *ts)
fun plus(vararg ts: Any?) = listOf("plus", *ts)
fun program(vararg ts: Any?) = listOf("program", *ts)
fun programming(vararg ts: Any?) = listOf("programming", *ts)
fun script(vararg ts: Any?) = listOf("script", *ts)
fun times(vararg ts: Any?) = listOf("times", *ts)
fun two(vararg ts: Any?) = listOf("two", *ts)
fun zero(vararg ts: Any?) = listOf("zero", *ts)
