package leo25

val applyName = "apply"
val anyName = "any"
val beName = "be"
val doName = "do"
val doingName = "doing"
val evaluateName = "evaluate"
val getName = "get"
val givenName = "given"
val hashName = "hash"
val isName = "is"
val letName = "let"
val makeName = "make"
val nativeName = "native"
val noName = "no"
val numberName = "number"
val recurseName = "recurse"
val recursingName = "recursing"
val repeatName = "repeat"
val repeatingName = "repeating"
val scriptName = "script"
val switchName = "switch"
val textName = "text"
val yesName = "yes"
