package leo25

val applyName = "apply"
val anyName = "any"
val becomeName = "become"
val commentName = "comment"
val doName = "do"
val doingName = "doing"
val evaluateName = "evaluate"
val getName = "get"
val letName = "let"
val nativeName = "native"
val recurseName = "recurse"
val recursingName = "recursing"
val repeatName = "repeat"
val repeatingName = "repeating"
val scriptName = "script"
val setName = "set"
val switchName = "switch"
