package leo25

val applyName = "apply"
val anyName = "any"
val asName = "as"
val becomeName = "become"
val causeName = "cause"
val commentName = "comment"
val doName = "do"
val doingName = "doing"
val errorName = "error"
val evaluateName = "evaluate"
val equalsName = "equals"
val hashName = "hash"
val letName = "let"
val nativeName = "native"
val noName = "no"
val numberName = "number"
val privateName = "private"
val recurseName = "recurse"
val recursingName = "recursing"
val resolveName = "resolve"
val repeatName = "repeat"
val repeatingName = "repeating"
val scriptName = "script"
val syntaxName = "syntax"
val switchName = "switch"
val textName = "text"
val traceName = "trace"
val useName = "use"
val yesName = "yes"

