bit
contains
	either zero
	either one

not bit zero
gives bit one

not bit one
gives bit zero

bit zero
and bit zero
gives bit zero

bit zero
and bit one
gives bit zero

bit one
and bit zero
gives bit zero

bit one
and bit one
gives bit one

bit zero
or bit zero
gives bit zero

bit zero
or bit one
gives bit one

bit one
or bit zero
gives bit one

bit one
or bit one
gives bit one

bit
nand bit
gives not
	the first operand
	and the second operand
