package leo14.untyped.dsl2

// TODO: Auto-generate this file

fun X.any(f: F) = x("any", f)
fun X.anything(f: F) = x("anything", f)
fun X.append(f: F) = x("append", f)
fun X.apply(f: F) = x("apply", f)
fun X._as(f: F) = x("as", f)
fun X.author(f: F) = x("author", f)
fun X.decrement(f: F) = x("decrement", f)
fun X.delete(f: F) = x("delete", f)
fun X._do(f: F) = x("do", f)
fun X.does(f: F) = x("does", f)
fun X._else(f: F) = x("else", f)
fun X._equals(f: F) = x("equals", f)
fun X.function(f: F) = x("function", f)
fun X.get(f: F) = x("get", f)
fun X.given(f: F) = x("given", f)
fun X.gives(f: F) = x("gives", f)
fun X.increment(f: F) = x("increment", f)
fun X.invoke(f: F) = x("invoke", f)
fun X._if(f: F) = x("if", f)
fun X._is(f: F) = x("is", f)
fun X.java(f: F) = x("java", f)
fun X.leonardo(f: F) = x("leonardo", f)
fun X.make(f: F) = x("make", f)
fun X.minus(f: F) = x("minus", f)
fun X.my(f: F) = x("my", f)
fun X.number(f: F) = x("number", f)
fun X.plus(f: F) = x("plus", f)
fun X.point(f: F) = x("point", f)
fun X.print(f: F) = x("print", f)
fun X.quote(f: F) = x("quote", f)
fun X.save(f: F) = x("save", f)
fun X.set(f: F) = x("set", f)
fun X.text(f: F) = x("text", f)
fun X._then(f: F) = x("then", f)
fun X._this(f: F) = x("this", f)
fun X.times(f: F) = x("times", f)
fun X.unquote(f: F) = x("unquote", f)
fun X.vector(f: F) = x("vector", f)
fun X.x(f: F) = x("x", f)
fun X.y(f: F) = x("y", f)
fun X.z(f: F) = x("z", f)

val X.any get() = any { this }
val X.anything get() = anything { this }
val X.append get() = append { this }
val X.apply get() = apply { this }
val X._as get() = _as { this }
val X.author get() = author { this }
val X.decrement get() = decrement { this }
val X.delete get() = delete { this }
val X._do get() = _do { this }
val X.does get() = does { this }
val X._else get() = _else { this }
val X.equals get() = equals { this }
val X.function get() = function { this }
val X.get get() = get { this }
val X.given get() = given { this }
val X.gives get() = gives { this }
val X.increment get() = increment { this }
val X.invoke get() = invoke { this }
val X._if get() = _if { this }
val X._is get() = _is { this }
val X.java get() = java { this }
val X.leonardo get() = leonardo { this }
val X.make get() = make { this }
val X.minus get() = minus { this }
val X.my get() = my { this }
val X.number get() = number { this }
val X.plus get() = plus { this }
val X.point get() = point { this }
val X.print get() = print { this }
val X.quote get() = quote { this }
val X.save get() = save { this }
val X.set get() = set { this }
val X.text get() = text { this }
val X._then get() = _then { this }
val X._this get() = _this { this }
val X.times get() = times { this }
val X.unquote get() = unquote { this }
val X.vector get() = vector { this }
val X.x get() = x { this }
val X.y get() = y { this }
val X.z get() = z { this }
