package leo14.untyped.dsl2

fun X.a(f: F): X = x("a", f)
fun X.above(f: F): X = x("above", f)
fun X.abs(f: F): X = x("abs", f)
fun X.absent(f: F): X = x("absent", f)
fun X.absolute(f: F): X = x("absolute", f)
fun X.abstract(f: F): X = x("abstract", f)
fun X.abstraction(f: F): X = x("abstraction", f)
fun X.accept(f: F): X = x("accept", f)
fun X.access(f: F): X = x("access", f)
fun X.accessible(f: F): X = x("accessible", f)
fun X.acos(f: F): X = x("acos", f)
fun X.activity(f: F): X = x("activity", f)
fun X.actual(f: F): X = x("actual", f)
fun X.add(f: F): X = x("add", f)
fun X.addr(f: F): X = x("addr", f)
fun X.address(f: F): X = x("address", f)
fun X.admin(f: F): X = x("admin", f)
fun X.after(f: F): X = x("after", f)
fun X.age(f: F): X = x("age", f)
fun X.all(f: F): X = x("all", f)
fun X.alloc(f: F): X = x("alloc", f)
fun X.allocate(f: F): X = x("allocate", f)
fun X.alpha(f: F): X = x("alpha", f)
fun X.always(f: F): X = x("always", f)
fun X.am(f: F): X = x("am", f)
fun X.amplitude(f: F): X = x("amplitude", f)
fun X.anchor(f: F): X = x("anchor", f)
fun X.and(f: F): X = x("and", f)
fun X.angle(f: F): X = x("angle", f)
fun X.anon(f: F): X = x("anon", f)
fun X.antialias(f: F): X = x("antialias", f)
fun X.antialiasing(f: F): X = x("antialiasing", f)
fun X.anticlockwise(f: F): X = x("anticlockwise", f)
fun X.any(f: F): X = x("any", f)
fun X.anything(f: F): X = x("anything", f)
fun X.appearance(f: F): X = x("appearance", f)
fun X.append(f: F): X = x("append", f)
fun X.appending(f: F): X = x("appending", f)
fun X.application(f: F): X = x("application", f)
fun X.applicative(f: F): X = x("applicative", f)
fun X.applier(f: F): X = x("applier", f)
fun X.apply(f: F): X = x("apply", f)
fun X.arc(f: F): X = x("arc", f)
fun X.area(f: F): X = x("area", f)
fun X.arg(f: F): X = x("arg", f)
fun X.argb(f: F): X = x("argb", f)
fun X.args(f: F): X = x("args", f)
fun X.argument(f: F): X = x("argument", f)
fun X.arguments(f: F): X = x("arguments", f)
fun X.arity(f: F): X = x("arity", f)
fun X.arr(f: F): X = x("arr", f)
fun X.array(f: F): X = x("array", f)
fun X.arraycopy(f: F): X = x("arraycopy", f)
fun X.arrow(f: F): X = x("arrow", f)
fun X.as_(f: F): X = x("as", f)
fun X.asin(f: F): X = x("asin", f)
fun X.assert(f: F): X = x("assert", f)
fun X.assignable(f: F): X = x("assignable", f)
fun X.async(f: F): X = x("async", f)
fun X.at(f: F): X = x("at", f)
fun X.atan(f: F): X = x("atan", f)
fun X.attention(f: F): X = x("attention", f)
fun X.attr(f: F): X = x("attr", f)
fun X.attribute(f: F): X = x("attribute", f)
fun X.audio(f: F): X = x("audio", f)
fun X.awt(f: F): X = x("awt", f)
fun X.b(f: F): X = x("b", f)
fun X.back(f: F): X = x("back", f)
fun X.background(f: F): X = x("background", f)
fun X.backslash(f: F): X = x("backslash", f)
fun X.backtrace(f: F): X = x("backtrace", f)
fun X.ball(f: F): X = x("ball", f)
fun X.ban(f: F): X = x("ban", f)
fun X.base(f: F): X = x("base", f)
fun X.becomes(f: F): X = x("becomes", f)
fun X.before(f: F): X = x("before", f)
fun X.begin(f: F): X = x("begin", f)
fun X.being(f: F): X = x("being", f)
fun X.below(f: F): X = x("below", f)
fun X.big(f: F): X = x("big", f)
fun X.binary(f: F): X = x("binary", f)
fun X.bind(f: F): X = x("bind", f)
fun X.bindings(f: F): X = x("bindings", f)
fun X.bit(f: F): X = x("bit", f)
fun X.black(f: F): X = x("black", f)
fun X.block(f: F): X = x("block", f)
fun X.blue(f: F): X = x("blue", f)
fun X.body(f: F): X = x("body", f)
fun X.bool(f: F): X = x("bool", f)
fun X.boolean(f: F): X = x("boolean", f)
fun X.booleans(f: F): X = x("booleans", f)
fun X.boost(f: F): X = x("boost", f)
fun X.bottom(f: F): X = x("bottom", f)
fun X.bounds(f: F): X = x("bounds", f)
fun X.bold(f: F): X = x("bold", f)
fun X.box(f: F): X = x("box", f)
fun X.bpm(f: F): X = x("bpm", f)
fun X.branch(f: F): X = x("branch", f)
fun X.buf(f: F): X = x("buf", f)
fun X.buffer(f: F): X = x("buffer", f)
fun X.build(f: F): X = x("build", f)
fun X.builder(f: F): X = x("builder", f)
fun X.by(f: F): X = x("by", f)
fun X.byte(f: F): X = x("byte", f)
fun X.bytes(f: F): X = x("bytes", f)
fun X.c(f: F): X = x("c", f)
fun X.cache(f: F): X = x("cache", f)
fun X.call(f: F): X = x("call", f)
fun X.called(f: F): X = x("called", f)
fun X.calling(f: F): X = x("calling", f)
fun X.cancel(f: F): X = x("cancel", f)
fun X.cancelable(f: F): X = x("cancelable", f)
fun X.cancelled(f: F): X = x("cancelled", f)
fun X.canvas(f: F): X = x("canvas", f)
fun X.cap(f: F): X = x("cap", f)
fun X.caps(f: F): X = x("caps", f)
fun X.case(f: F): X = x("case", f)
fun X.cast(f: F): X = x("cast", f)
fun X.catching(f: F): X = x("catching", f)
fun X.cause(f: F): X = x("cause", f)
fun X.caution(f: F): X = x("caution", f)
fun X.center(f: F): X = x("center", f)
fun X.chain(f: F): X = x("chain", f)
fun X.change(f: F): X = x("change", f)
fun X.char(f: F): X = x("char", f)
fun X.character(f: F): X = x("character", f)
fun X.cheat(f: F): X = x("cheat", f)
fun X.check(f: F): X = x("check", f)
fun X.checked(f: F): X = x("checked", f)
fun X.child(f: F): X = x("child", f)
fun X.children(f: F): X = x("children", f)
fun X.circle(f: F): X = x("circle", f)
fun X.class_(f: F): X = x("class", f)
fun X.classes(f: F): X = x("classes", f)
fun X.clear(f: F): X = x("clear", f)
fun X.click(f: F): X = x("click", f)
fun X.clip(f: F): X = x("clip", f)
fun X.clock(f: F): X = x("clock", f)
fun X.clockwise(f: F): X = x("clockwise", f)
fun X.clone(f: F): X = x("clone", f)
fun X.clones(f: F): X = x("clones", f)
fun X.close(f: F): X = x("close", f)
fun X.closeable(f: F): X = x("closeable", f)
fun X.closed(f: F): X = x("closed", f)
fun X.closure(f: F): X = x("closure", f)
fun X.code(f: F): X = x("code", f)
fun X.codeblock(f: F): X = x("codeblock", f)
fun X.codegen(f: F): X = x("codegen", f)
fun X.collect(f: F): X = x("collect", f)
fun X.collecting(f: F): X = x("collecting", f)
fun X.color(f: F): X = x("color", f)
fun X.colors(f: F): X = x("colors", f)
fun X.column(f: F): X = x("column", f)
fun X.columns(f: F): X = x("columns", f)
fun X.com(f: F): X = x("com", f)
fun X.comfort(f: F): X = x("comfort", f)
fun X.comma(f: F): X = x("comma", f)
fun X.command(f: F): X = x("command", f)
fun X.comment(f: F): X = x("comment", f)
fun X.common(f: F): X = x("common", f)
fun X.compact(f: F): X = x("compact", f)
fun X.compare(f: F): X = x("compare", f)
fun X.compass(f: F): X = x("compass", f)
fun X.component(f: F): X = x("component", f)
fun X.components(f: F): X = x("components", f)
fun X.compute(f: F): X = x("compute", f)
fun X.concat(f: F): X = x("concat", f)
fun X.condition(f: F): X = x("condition", f)
fun X.conflicts(f: F): X = x("conflicts", f)
fun X.connect(f: F): X = x("connect", f)
fun X.connected(f: F): X = x("connected", f)
fun X.connection(f: F): X = x("connection", f)
fun X.connections(f: F): X = x("connections", f)
fun X.console(f: F): X = x("console", f)
fun X.const(f: F): X = x("const", f)
fun X.constant(f: F): X = x("constant", f)
fun X.constructor(f: F): X = x("constructor", f)
fun X.constructors(f: F): X = x("constructors", f)
fun X.constructs(f: F): X = x("constructs", f)
fun X.constuctor(f: F): X = x("constuctor", f)
fun X.consumer(f: F): X = x("consumer", f)
fun X.consumers(f: F): X = x("consumers", f)
fun X.contain(f: F): X = x("contain", f)
fun X.contains(f: F): X = x("contains", f)
fun X.content(f: F): X = x("content", f)
fun X.context(f: F): X = x("context", f)
fun X.continuous(f: F): X = x("continuous", f)
fun X.control(f: F): X = x("control", f)
fun X.convert(f: F): X = x("convert", f)
fun X.coord(f: F): X = x("coord", f)
fun X.coordinate(f: F): X = x("coordinate", f)
fun X.coordinates(f: F): X = x("coordinates", f)
fun X.coords(f: F): X = x("coords", f)
fun X.copies(f: F): X = x("copies", f)
fun X.copy(f: F): X = x("copy", f)
fun X.cos(f: F): X = x("cos", f)
fun X.cosh(f: F): X = x("cosh", f)
fun X.count(f: F): X = x("count", f)
fun X.counter(f: F): X = x("counter", f)
fun X.cout(f: F): X = x("cout", f)
fun X.cover(f: F): X = x("cover", f)
fun X.crash(f: F): X = x("crash", f)
fun X.create(f: F): X = x("create", f)
fun X.created(f: F): X = x("created", f)
fun X.ctor(f: F): X = x("ctor", f)
fun X.current(f: F): X = x("current", f)
fun X.curve(f: F): X = x("curve", f)
fun X.cut(f: F): X = x("cut", f)
fun X.cyan(f: F): X = x("cyan", f)
fun X.d(f: F): X = x("d", f)
fun X.dare(f: F): X = x("dare", f)
fun X.dark(f: F): X = x("dark", f)
fun X.data(f: F): X = x("data", f)
fun X.database(f: F): X = x("database", f)
fun X.day(f: F): X = x("day", f)
fun X.debug(f: F): X = x("debug", f)
fun X.declaration(f: F): X = x("declaration", f)
fun X.declared(f: F): X = x("declared", f)
fun X.declaring(f: F): X = x("declaring", f)
fun X.decrement(f: F): X = x("decrement", f)
fun X.deepnight(f: F): X = x("deepnight", f)
fun X.def(f: F): X = x("def", f)
fun X.default(f: F): X = x("default", f)
fun X.define(f: F): X = x("define", f)
fun X.degrees(f: F): X = x("degrees", f)
fun X.delete(f: F): X = x("delete", f)
fun X.demo(f: F): X = x("demo", f)
fun X.depth(f: F): X = x("depth", f)
fun X.derive(f: F): X = x("derive", f)
fun X.describe(f: F): X = x("describe", f)
fun X.destroy(f: F): X = x("destroy", f)
fun X.detector(f: F): X = x("detector", f)
fun X.dict(f: F): X = x("dict", f)
fun X.dictionary(f: F): X = x("dictionary", f)
fun X.did(f: F): X = x("did", f)
fun X.difference(f: F): X = x("difference", f)
fun X.digest(f: F): X = x("digest", f)
fun X.dimensions(f: F): X = x("dimensions", f)
fun X.direct(f: F): X = x("direct", f)
fun X.display(f: F): X = x("display", f)
fun X.div(f: F): X = x("div", f)
fun X.divide(f: F): X = x("divide", f)
fun X.divided(f: F): X = x("divided", f)
fun X.divmod(f: F): X = x("divmod", f)
fun X.do_(f: F): X = x("do", f)
fun X.document(f: F): X = x("document", f)
fun X.does(f: F): X = x("does", f)
fun X.doing(f: F): X = x("doing", f)
fun X.done(f: F): X = x("done", f)
fun X.dot(f: F): X = x("dot", f)
fun X.double(f: F): X = x("double", f)
fun X.dp(f: F): X = x("dp", f)
fun X.draw(f: F): X = x("draw", f)
fun X.drawing(f: F): X = x("drawing", f)
fun X.ds(f: F): X = x("ds", f)
fun X.duty(f: F): X = x("duty", f)
fun X.dynamic(f: F): X = x("dynamic", f)
fun X.dynamics(f: F): X = x("dynamics", f)
fun X.e(f: F): X = x("e", f)
fun X.each(f: F): X = x("each", f)
fun X.edge(f: F): X = x("edge", f)
fun X.eight(f: F): X = x("eight", f)
fun X.either(f: F): X = x("either", f)
fun X.element(f: F): X = x("element", f)
fun X.elements(f: F): X = x("elements", f)
fun X.else_(f: F): X = x("else", f)
fun X.email(f: F): X = x("email", f)
fun X.empty(f: F): X = x("empty", f)
fun X.end(f: F): X = x("end", f)
fun X.ends(f: F): X = x("ends", f)
fun X.enter(f: F): X = x("enter", f)
fun X.entries(f: F): X = x("entries", f)
fun X.entry(f: F): X = x("entry", f)
fun X.enum(f: F): X = x("enum", f)
fun X.enums(f: F): X = x("enums", f)
fun X.eq(f: F): X = x("eq", f)
fun X.equal(f: F): X = x("equal", f)
fun X.equals_(f: F): X = x("equals", f)
fun X.equatable(f: F): X = x("equatable", f)
fun X.error(f: F): X = x("error", f)
fun X.esc(f: F): X = x("esc", f)
fun X.escape(f: F): X = x("escape", f)
fun X.eval(f: F): X = x("eval", f)
fun X.evaluate(f: F): X = x("evaluate", f)
fun X.evaluated(f: F): X = x("evaluated", f)
fun X.event(f: F): X = x("event", f)
fun X.events(f: F): X = x("events", f)
fun X.exactly(f: F): X = x("exactly", f)
fun X.examples(f: F): X = x("examples", f)
fun X.exception(f: F): X = x("exception", f)
fun X.exceptions(f: F): X = x("exceptions", f)
fun X.exclusive(f: F): X = x("exclusive", f)
fun X.exec(f: F): X = x("exec", f)
fun X.executable(f: F): X = x("executable", f)
fun X.execute(f: F): X = x("execute", f)
fun X.execution(f: F): X = x("execution", f)
fun X.executor(f: F): X = x("executor", f)
fun X.exists(f: F): X = x("exists", f)
fun X.exit(f: F): X = x("exit", f)
fun X.expand(f: F): X = x("expand", f)
fun X.expanded(f: F): X = x("expanded", f)
fun X.expands(f: F): X = x("expands", f)
fun X.expected(f: F): X = x("expected", f)
fun X.expression(f: F): X = x("expression", f)
fun X.ext(f: F): X = x("ext", f)
fun X.extends(f: F): X = x("extends", f)
fun X.extractor(f: F): X = x("extractor", f)
fun X.f(f: F): X = x("f", f)
fun X.f32(f: F): X = x("f32", f)
fun X.f64(f: F): X = x("f64", f)
fun X.factory(f: F): X = x("factory", f)
fun X.fading(f: F): X = x("fading", f)
fun X.failed(f: F): X = x("failed", f)
fun X.failures(f: F): X = x("failures", f)
fun X.false_(f: F): X = x("false", f)
fun X.family(f: F): X = x("family", f)
fun X.fast(f: F): X = x("fast", f)
fun X.father(f: F): X = x("father", f)
fun X.female(f: F): X = x("female", f)
fun X.fetch(f: F): X = x("fetch", f)
fun X.fib(f: F): X = x("fib", f)
fun X.field(f: F): X = x("field", f)
fun X.fields(f: F): X = x("fields", f)
fun X.file(f: F): X = x("file", f)
fun X.files(f: F): X = x("files", f)
fun X.fill(f: F): X = x("fill", f)
fun X.filter(f: F): X = x("filter", f)
fun X.final(f: F): X = x("final", f)
fun X.finality(f: F): X = x("finality", f)
fun X.finalizer(f: F): X = x("finalizer", f)
fun X.find(f: F): X = x("find", f)
fun X.finite(f: F): X = x("finite", f)
fun X.first(f: F): X = x("first", f)
fun X.five(f: F): X = x("five", f)
fun X.flat(f: F): X = x("flat", f)
fun X.flip(f: F): X = x("flip", f)
fun X.float(f: F): X = x("float", f)
fun X.float32(f: F): X = x("float32", f)
fun X.float64(f: F): X = x("float64", f)
fun X.floating(f: F): X = x("floating", f)
fun X.flush(f: F): X = x("flush", f)
fun X.fn(f: F): X = x("fn", f)
fun X.fold(f: F): X = x("fold", f)
fun X.folded(f: F): X = x("folded", f)
fun X.folder(f: F): X = x("folder", f)
fun X.font(f: F): X = x("font", f)
fun X.footer(f: F): X = x("footer", f)
fun X.for_(f: F): X = x("for", f)
fun X.force(f: F): X = x("force", f)
fun X.forced(f: F): X = x("forced", f)
fun X.foreground(f: F): X = x("foreground", f)
fun X.forget(f: F): X = x("forget", f)
fun X.form(f: F): X = x("form", f)
fun X.found(f: F): X = x("found", f)
fun X.four(f: F): X = x("four", f)
fun X.fragment(f: F): X = x("fragment", f)
fun X.frame(f: F): X = x("frame", f)
fun X.free(f: F): X = x("free", f)
fun X.freeze(f: F): X = x("freeze", f)
fun X.frequency(f: F): X = x("frequency", f)
fun X.from(f: F): X = x("from", f)
fun X.frozen(f: F): X = x("frozen", f)
fun X.full(f: F): X = x("full", f)
fun X.fully(f: F): X = x("fully", f)
fun X.fun_(f: F): X = x("fun", f)
fun X.func(f: F): X = x("func", f)
fun X.function(f: F): X = x("function", f)
fun X.functions(f: F): X = x("functions", f)
fun X.functor(f: F): X = x("functor", f)
fun X.future(f: F): X = x("future", f)
fun X.futures(f: F): X = x("futures", f)
fun X.g(f: F): X = x("g", f)
fun X.game(f: F): X = x("game", f)
fun X.gen(f: F): X = x("gen", f)
fun X.generic(f: F): X = x("generic", f)
fun X.generics(f: F): X = x("generics", f)
fun X.get(f: F): X = x("get", f)
fun X.gets(f: F): X = x("gets", f)
fun X.getting(f: F): X = x("getting", f)
fun X.give(f: F): X = x("give", f)
fun X.given(f: F): X = x("given", f)
fun X.gives(f: F): X = x("gives", f)
fun X.global(f: F): X = x("global", f)
fun X.glyph(f: F): X = x("glyph", f)
fun X.google(f: F): X = x("google", f)
fun X.gray(f: F): X = x("gray", f)
fun X.green(f: F): X = x("green", f)
fun X.grey(f: F): X = x("grey", f)
fun X.grid(f: F): X = x("grid", f)
fun X.h(f: F): X = x("h", f)
fun X.h1(f: F): X = x("h1", f)
fun X.h2(f: F): X = x("h2", f)
fun X.h3(f: F): X = x("h3", f)
fun X.h4(f: F): X = x("h4", f)
fun X.h5(f: F): X = x("h5", f)
fun X.h6(f: F): X = x("h6", f)
fun X.hack(f: F): X = x("hack", f)
fun X.hacker(f: F): X = x("hacker", f)
fun X.handle(f: F): X = x("handle", f)
fun X.has(f: F): X = x("has", f)
fun X.hash(f: F): X = x("hash", f)
fun X.hashes(f: F): X = x("hashes", f)
fun X.haxe(f: F): X = x("haxe", f)
fun X.head(f: F): X = x("head", f)
fun X.header(f: F): X = x("header", f)
fun X.heap(f: F): X = x("heap", f)
fun X.height(f: F): X = x("height", f)
fun X.heights(f: F): X = x("heights", f)
fun X.hi(f: F): X = x("hi", f)
fun X.high(f: F): X = x("high", f)
fun X.hint(f: F): X = x("hint", f)
fun X.holder(f: F): X = x("holder", f)
fun X.horizontal(f: F): X = x("horizontal", f)
fun X.horizontally(f: F): X = x("horizontally", f)
fun X.host(f: F): X = x("host", f)
fun X.hour(f: F): X = x("hour", f)
fun X.href(f: F): X = x("href", f)
fun X.html(f: F): X = x("html", f)
fun X.http(f: F): X = x("http", f)
fun X.husband(f: F): X = x("husband", f)
fun X.hx(f: F): X = x("hx", f)
fun X.i(f: F): X = x("i", f)
fun X.icon(f: F): X = x("icon", f)
fun X.identifier(f: F): X = x("identifier", f)
fun X.identifiers(f: F): X = x("identifiers", f)
fun X.if_(f: F): X = x("if", f)
fun X.immediate(f: F): X = x("immediate", f)
fun X.immutable(f: F): X = x("immutable", f)
fun X.impl(f: F): X = x("impl", f)
fun X.implement(f: F): X = x("implement", f)
fun X.implements(f: F): X = x("implements", f)
fun X.import(f: F): X = x("import", f)
fun X.in_(f: F): X = x("in", f)
fun X.inbpm(f: F): X = x("inbpm", f)
fun X.increment(f: F): X = x("increment", f)
fun X.indent(f: F): X = x("indent", f)
fun X.index(f: F): X = x("index", f)
fun X.infinite(f: F): X = x("infinite", f)
fun X.info(f: F): X = x("info", f)
fun X.inherit(f: F): X = x("inherit", f)
fun X.init(f: F): X = x("init", f)
fun X.initial(f: F): X = x("initial", f)
fun X.initializer(f: F): X = x("initializer", f)
fun X.inline(f: F): X = x("inline", f)
fun X.input(f: F): X = x("input", f)
fun X.insert(f: F): X = x("insert", f)
fun X.instance(f: F): X = x("instance", f)
fun X.instrument(f: F): X = x("instrument", f)
fun X.instruments(f: F): X = x("instruments", f)
fun X.i1(f: F): X = x("i1", f)
fun X.i2(f: F): X = x("i2", f)
fun X.i4(f: F): X = x("i4", f)
fun X.i8(f: F): X = x("i8", f)
fun X.i16(f: F): X = x("i16", f)
fun X.i32(f: F): X = x("i32", f)
fun X.i64(f: F): X = x("i64", f)
fun X.image(f: F): X = x("image", f)
fun X.int(f: F): X = x("int", f)
fun X.int16(f: F): X = x("int16", f)
fun X.int32(f: F): X = x("int32", f)
fun X.int64(f: F): X = x("int64", f)
fun X.int8(f: F): X = x("int8", f)
fun X.integer(f: F): X = x("integer", f)
fun X.integers(f: F): X = x("integers", f)
fun X.integral(f: F): X = x("integral", f)
fun X.intent(f: F): X = x("intent", f)
fun X.intercept(f: F): X = x("intercept", f)
fun X.interface_(f: F): X = x("interface", f)
fun X.intern(f: F): X = x("intern", f)
fun X.interrupt(f: F): X = x("interrupt", f)
fun X.inventory(f: F): X = x("inventory", f)
fun X.invoke(f: F): X = x("invoke", f)
fun X.ios(f: F): X = x("ios", f)
fun X.ipad(f: F): X = x("ipad", f)
fun X.iphone(f: F): X = x("iphone", f)
fun X.is_(f: F): X = x("is", f)
fun X.it(f: F): X = x("it", f)
fun X.iterable(f: F): X = x("iterable", f)
fun X.iterables(f: F): X = x("iterables", f)
fun X.iteratively(f: F): X = x("iteratively", f)
fun X.iterator(f: F): X = x("iterator", f)
fun X.iterators(f: F): X = x("iterators", f)
fun X.itself(f: F): X = x("itself", f)
fun X.j(f: F): X = x("j", f)
fun X.jam(f: F): X = x("jam", f)
fun X.jar(f: F): X = x("jar", f)
fun X.java(f: F): X = x("java", f)
fun X.join(f: F): X = x("join", f)
fun X.jump(f: F): X = x("jump", f)
fun X.just(f: F): X = x("just", f)
fun X.k(f: F): X = x("k", f)
fun X.key(f: F): X = x("key", f)
fun X.keyboard(f: F): X = x("keyboard", f)
fun X.keyword(f: F): X = x("keyword", f)
fun X.kick(f: F): X = x("kick", f)
fun X.kotlin(f: F): X = x("kotlin", f)
fun X.l(f: F): X = x("l", f)
fun X.label(f: F): X = x("label", f)
fun X.lambda(f: F): X = x("lambda", f)
fun X.lang(f: F): X = x("lang", f)
fun X.last(f: F): X = x("last", f)
fun X.latch(f: F): X = x("latch", f)
fun X.lazily(f: F): X = x("lazily", f)
fun X.lazy_(f: F): X = x("lazy", f)
fun X.left(f: F): X = x("left", f)
fun X.len(f: F): X = x("len", f)
fun X.length(f: F): X = x("length", f)
fun X.lengths(f: F): X = x("lengths", f)
fun X.leo(f: F): X = x("leo", f)
fun X.leonardo(f: F): X = x("leonardo", f)
fun X.leonize(f: F): X = x("leonize", f)
fun X.leonized(f: F): X = x("leonized", f)
fun X.leonizer(f: F): X = x("leonizer", f)
fun X.lhs(f: F): X = x("lhs", f)
fun X.lib(f: F): X = x("lib", f)
fun X.library(f: F): X = x("library", f)
fun X.light(f: F): X = x("light", f)
fun X.line(f: F): X = x("line", f)
fun X.lines(f: F): X = x("lines", f)
fun X.linked(f: F): X = x("linked", f)
fun X.list(f: F): X = x("list", f)
fun X.listener(f: F): X = x("listener", f)
fun X.lists(f: F): X = x("lists", f)
fun X.literal(f: F): X = x("literal", f)
fun X.lo(f: F): X = x("lo", f)
fun X.load(f: F): X = x("load", f)
fun X.loader(f: F): X = x("loader", f)
fun X.lock(f: F): X = x("lock", f)
fun X.log(f: F): X = x("log", f)
fun X.login(f: F): X = x("login", f)
fun X.logo(f: F): X = x("logo", f)
fun X.logout(f: F): X = x("logout", f)
fun X.lol(f: F): X = x("lol", f)
fun X.long(f: F): X = x("long", f)
fun X.look(f: F): X = x("look", f)
fun X.lookup(f: F): X = x("lookup", f)
fun X.loop(f: F): X = x("loop", f)
fun X.lost(f: F): X = x("lost", f)
fun X.low(f: F): X = x("low", f)
fun X.lower(f: F): X = x("lower", f)
fun X.ludum(f: F): X = x("ludum", f)
fun X.ludumdare(f: F): X = x("ludumdare", f)
fun X.m(f: F): X = x("m", f)
fun X.mac(f: F): X = x("mac", f)
fun X.macos(f: F): X = x("macos", f)
fun X.macro(f: F): X = x("macro", f)
fun X.magenta(f: F): X = x("magenta", f)
fun X.mail(f: F): X = x("mail", f)
fun X.main(f: F): X = x("main", f)
fun X.make(f: F): X = x("make", f)
fun X.male(f: F): X = x("male", f)
fun X.manager(f: F): X = x("manager", f)
fun X.map(f: F): X = x("map", f)
fun X.mapping(f: F): X = x("mapping", f)
fun X.maps(f: F): X = x("maps", f)
fun X.mapt(f: F): X = x("mapt", f)
fun X.margin(f: F): X = x("margin", f)
fun X.marriage(f: F): X = x("marriage", f)
fun X.match(f: F): X = x("match", f)
fun X.matcher(f: F): X = x("matcher", f)
fun X.matches(f: F): X = x("matches", f)
fun X.matching(f: F): X = x("matching", f)
fun X.max(f: F): X = x("max", f)
fun X.maybe(f: F): X = x("maybe", f)
fun X.measure(f: F): X = x("measure", f)
fun X.melody(f: F): X = x("melody", f)
fun X.mem(f: F): X = x("mem", f)
fun X.member(f: F): X = x("member", f)
fun X.members(f: F): X = x("members", f)
fun X.membership(f: F): X = x("membership", f)
fun X.memory(f: F): X = x("memory", f)
fun X.merger(f: F): X = x("merger", f)
fun X.message(f: F): X = x("message", f)
fun X.meta(f: F): X = x("meta", f)
fun X.method(f: F): X = x("method", f)
fun X.methods(f: F): X = x("methods", f)
fun X.metrics(f: F): X = x("metrics", f)
fun X.micapolos(f: F): X = x("micapolos", f)
fun X.middle(f: F): X = x("middle", f)
fun X.millis(f: F): X = x("millis", f)
fun X.min(f: F): X = x("min", f)
fun X.minus(f: F): X = x("minus", f)
fun X.minute(f: F): X = x("minute", f)
fun X.miss(f: F): X = x("miss", f)
fun X.missing(f: F): X = x("missing", f)
fun X.mod(f: F): X = x("mod", f)
fun X.mode(f: F): X = x("mode", f)
fun X.modifier(f: F): X = x("modifier", f)
fun X.modifiers(f: F): X = x("modifiers", f)
fun X.module(f: F): X = x("module", f)
fun X.monad(f: F): X = x("monad", f)
fun X.month(f: F): X = x("month", f)
fun X.more(f: F): X = x("more", f)
fun X.mother(f: F): X = x("mother", f)
fun X.motion(f: F): X = x("motion", f)
fun X.mouse(f: F): X = x("mouse", f)
fun X.move(f: F): X = x("move", f)
fun X.mul(f: F): X = x("mul", f)
fun X.multiply(f: F): X = x("multiply", f)
fun X.mutable(f: F): X = x("mutable", f)
fun X.my(f: F): X = x("my", f)
fun X.n(f: F): X = x("n", f)
fun X.name(f: F): X = x("name", f)
fun X.named(f: F): X = x("named", f)
fun X.names(f: F): X = x("names", f)
fun X.nand(f: F): X = x("nand", f)
fun X.native(f: F): X = x("native", f)
fun X.negate(f: F): X = x("negate", f)
fun X.new(f: F): X = x("new", f)
fun X.newline(f: F): X = x("newline", f)
fun X.next(f: F): X = x("next", f)
fun X.night(f: F): X = x("night", f)
fun X.nil(f: F): X = x("nil", f)
fun X.nine(f: F): X = x("nine", f)
fun X.no(f: F): X = x("no", f)
fun X.node(f: F): X = x("node", f)
fun X.non(f: F): X = x("non", f)
fun X.none(f: F): X = x("none", f)
fun X.nor(f: F): X = x("nor", f)
fun X.not(f: F): X = x("not", f)
fun X.note(f: F): X = x("note", f)
fun X.notes(f: F): X = x("notes", f)
fun X.nothing(f: F): X = x("nothing", f)
fun X.now(f: F): X = x("now", f)
fun X.null_(f: F): X = x("null", f)
fun X.nullable(f: F): X = x("nullable", f)
fun X.number(f: F): X = x("number", f)
fun X.numbers(f: F): X = x("numbers", f)
fun X.o(f: F): X = x("o", f)
fun X.obj(f: F): X = x("obj", f)
fun X.object_(f: F): X = x("object", f)
fun X.objects(f: F): X = x("objects", f)
fun X.of(f: F): X = x("of", f)
fun X.off(f: F): X = x("off", f)
fun X.office(f: F): X = x("office", f)
fun X.offset(f: F): X = x("offset", f)
fun X.ofib(f: F): X = x("ofib", f)
fun X.on(f: F): X = x("on", f)
fun X.one(f: F): X = x("one", f)
fun X.only(f: F): X = x("only", f)
fun X.op(f: F): X = x("op", f)
fun X.open(f: F): X = x("open", f)
fun X.operation(f: F): X = x("operation", f)
fun X.operator(f: F): X = x("operator", f)
fun X.option(f: F): X = x("option", f)
fun X.optional(f: F): X = x("optional", f)
fun X.optionals(f: F): X = x("optionals", f)
fun X.or(f: F): X = x("or", f)
fun X.orange(f: F): X = x("orange", f)
fun X.order(f: F): X = x("order", f)
fun X.ordinal(f: F): X = x("ordinal", f)
fun X.org(f: F): X = x("org", f)
fun X.original(f: F): X = x("original", f)
fun X.otherwise(f: F): X = x("otherwise", f)
fun X.out(f: F): X = x("out", f)
fun X.outline(f: F): X = x("outline", f)
fun X.output(f: F): X = x("output", f)
fun X.oval(f: F): X = x("oval", f)
fun X.over(f: F): X = x("over", f)
fun X.overflow(f: F): X = x("overflow", f)
fun X.owner(f: F): X = x("owner", f)
fun X.p(f: F): X = x("p", f)
fun X.package_(f: F): X = x("package", f)
fun X.packages(f: F): X = x("packages", f)
fun X.page(f: F): X = x("page", f)
fun X.paint(f: F): X = x("paint", f)
fun X.pair(f: F): X = x("pair", f)
fun X.pane(f: F): X = x("pane", f)
fun X.param(f: F): X = x("param", f)
fun X.parameter(f: F): X = x("parameter", f)
fun X.parameters(f: F): X = x("parameters", f)
fun X.params(f: F): X = x("params", f)
fun X.parent(f: F): X = x("parent", f)
fun X.parentheses(f: F): X = x("parentheses", f)
fun X.parse(f: F): X = x("parse", f)
fun X.parser(f: F): X = x("parser", f)
fun X.pass(f: F): X = x("pass", f)
fun X.password(f: F): X = x("password", f)
fun X.paste(f: F): X = x("paste", f)
fun X.path(f: F): X = x("path", f)
fun X.pattern(f: F): X = x("pattern", f)
fun X.pause(f: F): X = x("pause", f)
fun X.payload(f: F): X = x("payload", f)
fun X.pc(f: F): X = x("pc", f)
fun X.percent(f: F): X = x("percent", f)
fun X.period(f: F): X = x("period", f)
fun X.person(f: F): X = x("person", f)
fun X.phase(f: F): X = x("phase", f)
fun X.phone(f: F): X = x("phone", f)
fun X.pi(f: F): X = x("pi", f)
fun X.pin(f: F): X = x("pin", f)
fun X.ping(f: F): X = x("ping", f)
fun X.pink(f: F): X = x("pink", f)
fun X.pins(f: F): X = x("pins", f)
fun X.pixel(f: F): X = x("pixel", f)
fun X.pkg(f: F): X = x("pkg", f)
fun X.plain(f: F): X = x("plain", f)
fun X.play(f: F): X = x("play", f)
fun X.plus(f: F): X = x("plus", f)
fun X.pm(f: F): X = x("pm", f)
fun X.point(f: F): X = x("point", f)
fun X.pong(f: F): X = x("pong", f)
fun X.pop(f: F): X = x("pop", f)
fun X.port(f: F): X = x("port", f)
fun X.position(f: F): X = x("position", f)
fun X.possible(f: F): X = x("possible", f)
fun X.post(f: F): X = x("post", f)
fun X.ppq(f: F): X = x("ppq", f)
fun X.predecessor(f: F): X = x("predecessor", f)
fun X.prefix(f: F): X = x("prefix", f)
fun X.preprocess(f: F): X = x("preprocess", f)
fun X.preprocessor(f: F): X = x("preprocessor", f)
fun X.present(f: F): X = x("present", f)
fun X.prev(f: F): X = x("prev", f)
fun X.previous(f: F): X = x("previous", f)
fun X.primitive(f: F): X = x("primitive", f)
fun X.print(f: F): X = x("print", f)
fun X.printed(f: F): X = x("printed", f)
fun X.printer(f: F): X = x("printer", f)
fun X.printing(f: F): X = x("printing", f)
fun X.println(f: F): X = x("println", f)
fun X.private(f: F): X = x("private", f)
fun X.process(f: F): X = x("process", f)
fun X.processed(f: F): X = x("processed", f)
fun X.producer(f: F): X = x("producer", f)
fun X.product(f: F): X = x("product", f)
fun X.program(f: F): X = x("program", f)
fun X.property(f: F): X = x("property", f)
fun X.protected(f: F): X = x("protected", f)
fun X.public(f: F): X = x("public", f)
fun X.pull(f: F): X = x("pull", f)
fun X.push(f: F): X = x("push", f)
fun X.put(f: F): X = x("put", f)
fun X.q(f: F): X = x("q", f)
fun X.query(f: F): X = x("query", f)
fun X.queue(f: F): X = x("queue", f)
fun X.quicksort(f: F): X = x("quicksort", f)
fun X.quote(f: F): X = x("quote", f)
fun X.quoted(f: F): X = x("quoted", f)
fun X.r(f: F): X = x("r", f)
fun X.radians(f: F): X = x("radians", f)
fun X.radius(f: F): X = x("radius", f)
fun X.random(f: F): X = x("random", f)
fun X.read(f: F): X = x("read", f)
fun X.reader(f: F): X = x("reader", f)
fun X.reading(f: F): X = x("reading", f)
fun X.readonly(f: F): X = x("readonly", f)
fun X.readutf(f: F): X = x("readutf", f)
fun X.recover(f: F): X = x("recover", f)
fun X.rect(f: F): X = x("rect", f)
fun X.rectangle(f: F): X = x("rectangle", f)
fun X.recurse(f: F): X = x("recurse", f)
fun X.recursion(f: F): X = x("recursion", f)
fun X.recursive(f: F): X = x("recursive", f)
fun X.recursively(f: F): X = x("recursively", f)
fun X.red(f: F): X = x("red", f)
fun X.redirect(f: F): X = x("redirect", f)
fun X.ref(f: F): X = x("ref", f)
fun X.reference(f: F): X = x("reference", f)
fun X.refl(f: F): X = x("refl", f)
fun X.reflect(f: F): X = x("reflect", f)
fun X.remainder(f: F): X = x("remainder", f)
fun X.remove(f: F): X = x("remove", f)
fun X.render(f: F): X = x("render", f)
fun X.rendering(f: F): X = x("rendering", f)
fun X.repeat(f: F): X = x("repeat", f)
fun X.replace(f: F): X = x("replace", f)
fun X.required(f: F): X = x("required", f)
fun X.reset(f: F): X = x("reset", f)
fun X.resolution(f: F): X = x("resolution", f)
fun X.resolve(f: F): X = x("resolve", f)
fun X.resolved(f: F): X = x("resolved", f)
fun X.resolver(f: F): X = x("resolver", f)
fun X.resource(f: F): X = x("resource", f)
fun X.result(f: F): X = x("result", f)
fun X.resume(f: F): X = x("resume", f)
fun X.resumed(f: F): X = x("resumed", f)
fun X.ret(f: F): X = x("ret", f)
fun X.reti(f: F): X = x("reti", f)
fun X.return_(f: F): X = x("return", f)
fun X.returns(f: F): X = x("returns", f)
fun X.reverse(f: F): X = x("reverse", f)
fun X.rgb(f: F): X = x("rgb", f)
fun X.rgba(f: F): X = x("rgba", f)
fun X.rhs(f: F): X = x("rhs", f)
fun X.right(f: F): X = x("right", f)
fun X.root(f: F): X = x("root", f)
fun X.rotate(f: F): X = x("rotate", f)
fun X.round(f: F): X = x("round", f)
fun X.row(f: F): X = x("row", f)
fun X.rows(f: F): X = x("rows", f)
fun X.rule(f: F): X = x("rule", f)
fun X.run(f: F): X = x("run", f)
fun X.running(f: F): X = x("running", f)
fun X.runtime(f: F): X = x("runtime", f)
fun X.s(f: F): X = x("s", f)
fun X.save(f: F): X = x("save", f)
fun X.sawtooth(f: F): X = x("sawtooth", f)
fun X.say(f: F): X = x("say", f)
fun X.scale(f: F): X = x("scale", f)
fun X.scheme(f: F): X = x("scheme", f)
fun X.scope(f: F): X = x("scope", f)
fun X.scoped(f: F): X = x("scoped", f)
fun X.scopes(f: F): X = x("scopes", f)
fun X.screen(f: F): X = x("screen", f)
fun X.script(f: F): X = x("script", f)
fun X.search(f: F): X = x("search", f)
fun X.second(f: F): X = x("second", f)
fun X.select(f: F): X = x("select", f)
fun X.self(f: F): X = x("self", f)
fun X.semicolon(f: F): X = x("semicolon", f)
fun X.sentinel(f: F): X = x("sentinel", f)
fun X.separated(f: F): X = x("separated", f)
fun X.separator(f: F): X = x("separator", f)
fun X.sequence(f: F): X = x("sequence", f)
fun X.sequencer(f: F): X = x("sequencer", f)
fun X.serial(f: F): X = x("serial", f)
fun X.server(f: F): X = x("server", f)
fun X.set(f: F): X = x("set", f)
fun X.sets(f: F): X = x("sets", f)
fun X.seven(f: F): X = x("seven", f)
fun X.sex(f: F): X = x("sex", f)
fun X.shape(f: F): X = x("shape", f)
fun X.shapes(f: F): X = x("shapes", f)
fun X.shift(f: F): X = x("shift", f)
fun X.short(f: F): X = x("short", f)
fun X.shortquote(f: F): X = x("shortquote", f)
fun X.show(f: F): X = x("show", f)
fun X.shutdown(f: F): X = x("shutdown", f)
fun X.side(f: F): X = x("side", f)
fun X.simple(f: F): X = x("simple", f)
fun X.sin(f: F): X = x("sin", f)
fun X.sine(f: F): X = x("sine", f)
fun X.single(f: F): X = x("single", f)
fun X.singleton(f: F): X = x("singleton", f)
fun X.singly(f: F): X = x("singly", f)
fun X.sinh(f: F): X = x("sinh", f)
fun X.sink(f: F): X = x("sink", f)
fun X.sinks(f: F): X = x("sinks", f)
fun X.six(f: F): X = x("six", f)
fun X.size(f: F): X = x("size", f)
fun X.skip(f: F): X = x("skip", f)
fun X.slash(f: F): X = x("slash", f)
fun X.sleep(f: F): X = x("sleep", f)
fun X.slice(f: F): X = x("slice", f)
fun X.sliding(f: F): X = x("sliding", f)
fun X.slow(f: F): X = x("slow", f)
fun X.some(f: F): X = x("some", f)
fun X.sort(f: F): X = x("sort", f)
fun X.source(f: F): X = x("source", f)
fun X.space(f: F): X = x("space", f)
fun X.span(f: F): X = x("span", f)
fun X.spanning(f: F): X = x("spanning", f)
fun X.splice(f: F): X = x("splice", f)
fun X.split(f: F): X = x("split", f)
fun X.spouse(f: F): X = x("spouse", f)
fun X.square(f: F): X = x("square", f)
fun X.squared(f: F): X = x("squared", f)
fun X.sr(f: F): X = x("sr", f)
fun X.src(f: F): X = x("src", f)
fun X.stack(f: F): X = x("stack", f)
fun X.stacks(f: F): X = x("stacks", f)
fun X.stand(f: F): X = x("stand", f)
fun X.start(f: F): X = x("start", f)
fun X.started(f: F): X = x("started", f)
fun X.starts(f: F): X = x("starts", f)
fun X.state(f: F): X = x("state", f)
fun X.statement(f: F): X = x("statement", f)
fun X.statements(f: F): X = x("statements", f)
fun X.static(f: F): X = x("static", f)
fun X.std(f: F): X = x("std", f)
fun X.step(f: F): X = x("step", f)
fun X.stop(f: F): X = x("stop", f)
fun X.stream(f: F): X = x("stream", f)
fun X.string(f: F): X = x("string", f)
fun X.strings(f: F): X = x("strings", f)
fun X.stroke(f: F): X = x("stroke", f)
fun X.struct(f: F): X = x("struct", f)
fun X.style(f: F): X = x("style", f)
fun X.sub(f: F): X = x("sub", f)
fun X.subject(f: F): X = x("subject", f)
fun X.submit(f: F): X = x("submit", f)
fun X.subpackages(f: F): X = x("subpackages", f)
fun X.substr(f: F): X = x("substr", f)
fun X.substring(f: F): X = x("substring", f)
fun X.subtract(f: F): X = x("subtract", f)
fun X.successor(f: F): X = x("successor", f)
fun X.suffix(f: F): X = x("suffix", f)
fun X.sum(f: F): X = x("sum", f)
fun X.super_(f: F): X = x("super", f)
fun X.superclass(f: F): X = x("superclass", f)
fun X.supervisor(f: F): X = x("supervisor", f)
fun X.supplier(f: F): X = x("supplier", f)
fun X.suppliers(f: F): X = x("suppliers", f)
fun X.suppressed(f: F): X = x("suppressed", f)
fun X.switch(f: F): X = x("switch", f)
fun X.symbol(f: F): X = x("symbol", f)
fun X.symbols(f: F): X = x("symbols", f)
fun X.syntax(f: F): X = x("syntax", f)
fun X.system(f: F): X = x("system", f)
fun X.t(f: F): X = x("t", f)
fun X.tab(f: F): X = x("tab", f)
fun X.tag(f: F): X = x("tag", f)
fun X.tail(f: F): X = x("tail", f)
fun X.tan(f: F): X = x("tan", f)
fun X.tanh(f: F): X = x("tanh", f)
fun X.tap(f: F): X = x("tap", f)
fun X.target(f: F): X = x("target", f)
fun X.temp(f: F): X = x("temp", f)
fun X.template(f: F): X = x("template", f)
fun X.tempo(f: F): X = x("tempo", f)
fun X.tempos(f: F): X = x("tempos", f)
fun X.ten(f: F): X = x("ten", f)
fun X.term(f: F): X = x("term", f)
fun X.terms(f: F): X = x("terms", f)
fun X.test(f: F): X = x("test", f)
fun X.testing(f: F): X = x("testing", f)
fun X.tests(f: F): X = x("tests", f)
fun X.text(f: F): X = x("text", f)
fun X.that(f: F): X = x("that", f)
fun X.the(f: F): X = x("the", f)
fun X.then_(f: F): X = x("then", f)
fun X.these(f: F): X = x("these", f)
fun X.third(f: F): X = x("third", f)
fun X.this_(f: F): X = x("this", f)
fun X.thread(f: F): X = x("thread", f)
fun X.three(f: F): X = x("three", f)
fun X.throw_(f: F): X = x("throw", f)
fun X.throwable(f: F): X = x("throwable", f)
fun X.throws(f: F): X = x("throws", f)
fun X.thunk(f: F): X = x("thunk", f)
fun X.time(f: F): X = x("time", f)
fun X.timeout(f: F): X = x("timeout", f)
fun X.times(f: F): X = x("times", f)
fun X.timestamp(f: F): X = x("timestamp", f)
fun X.to(f: F): X = x("to", f)
fun X.top(f: F): X = x("top", f)
fun X.touch(f: F): X = x("touch", f)
fun X.trace(f: F): X = x("trace", f)
fun X.traced(f: F): X = x("traced", f)
fun X.track(f: F): X = x("track", f)
fun X.transform(f: F): X = x("transform", f)
fun X.translate(f: F): X = x("translate", f)
fun X.triangle(f: F): X = x("triangle", f)
fun X.trigger(f: F): X = x("trigger", f)
fun X.true_(f: F): X = x("true", f)
fun X.truth(f: F): X = x("truth", f)
fun X.tuple(f: F): X = x("tuple", f)
fun X.two(f: F): X = x("two", f)
fun X.type(f: F): X = x("type", f)
fun X.types(f: F): X = x("types", f)
fun X.u(f: F): X = x("u", f)
fun X.uint(f: F): X = x("uint", f)
fun X.uint16(f: F): X = x("uint16", f)
fun X.uint32(f: F): X = x("uint32", f)
fun X.uint64(f: F): X = x("uint64", f)
fun X.uint8(f: F): X = x("uint8", f)
fun X.unchecked(f: F): X = x("unchecked", f)
fun X.undefined(f: F): X = x("undefined", f)
fun X.underscorify(f: F): X = x("underscorify", f)
fun X.undo(f: F): X = x("undo", f)
fun X.unhandled(f: F): X = x("unhandled", f)
fun X.unindent(f: F): X = x("unindent", f)
fun X.unit(f: F): X = x("unit", f)
fun X.unknown(f: F): X = x("unknown", f)
fun X.unmodifiable(f: F): X = x("unmodifiable", f)
fun X.unquote(f: F): X = x("unquote", f)
fun X.unquoted(f: F): X = x("unquoted", f)
fun X.unread(f: F): X = x("unread", f)
fun X.unresolved(f: F): X = x("unresolved", f)
fun X.unsafe(f: F): X = x("unsafe", f)
fun X.unsafes(f: F): X = x("unsafes", f)
fun X.unshift(f: F): X = x("unshift", f)
fun X.unsigned(f: F): X = x("unsigned", f)
fun X.update(f: F): X = x("update", f)
fun X.upper(f: F): X = x("upper", f)
fun X.uri(f: F): X = x("uri", f)
fun X.url(f: F): X = x("url", f)
fun X.use(f: F): X = x("use", f)
fun X.user(f: F): X = x("user", f)
fun X.util(f: F): X = x("util", f)
fun X.v(f: F): X = x("v", f)
fun X.val_(f: F): X = x("val", f)
fun X.value(f: F): X = x("value", f)
fun X.values(f: F): X = x("values", f)
fun X.var_(f: F): X = x("var", f)
fun X.variable(f: F): X = x("variable", f)
fun X.variables(f: F): X = x("variables", f)
fun X.vec(f: F): X = x("vec", f)
fun X.vec2(f: F): X = x("vec2", f)
fun X.vec3(f: F): X = x("vec3", f)
fun X.vec4(f: F): X = x("vec4", f)
fun X.vector(f: F): X = x("vector", f)
fun X.versionuid(f: F): X = x("versionuid", f)
fun X.vertical(f: F): X = x("vertical", f)
fun X.vertically(f: F): X = x("vertically", f)
fun X.view(f: F): X = x("view", f)
fun X.violet(f: F): X = x("violet", f)
fun X.visibility(f: F): X = x("visibility", f)
fun X.visible(f: F): X = x("visible", f)
fun X.visit(f: F): X = x("visit", f)
fun X.visitor(f: F): X = x("visitor", f)
fun X.void(f: F): X = x("void", f)
fun X.volume(f: F): X = x("volume", f)
fun X.w(f: F): X = x("w", f)
fun X.wait(f: F): X = x("wait", f)
fun X.warn(f: F): X = x("warn", f)
fun X.warning(f: F): X = x("warning", f)
fun X.watch(f: F): X = x("watch", f)
fun X.wave(f: F): X = x("wave", f)
fun X.weak(f: F): X = x("weak", f)
fun X.week(f: F): X = x("week", f)
fun X.while_(f: F): X = x("while", f)
fun X.white(f: F): X = x("white", f)
fun X.widget(f: F): X = x("widget", f)
fun X.width(f: F): X = x("width", f)
fun X.wife(f: F): X = x("wife", f)
fun X.win(f: F): X = x("win", f)
fun X.winding(f: F): X = x("winding", f)
fun X.window(f: F): X = x("window", f)
fun X.wire(f: F): X = x("wire", f)
fun X.with(f: F): X = x("with", f)
fun X.without(f: F): X = x("without", f)
fun X.word(f: F): X = x("word", f)
fun X.wrap(f: F): X = x("wrap", f)
fun X.write(f: F): X = x("write", f)
fun X.writes(f: F): X = x("writes", f)
fun X.writing(f: F): X = x("writing", f)
fun X.x(f: F): X = x("x", f)
fun X.xfib(f: F): X = x("xfib", f)
fun X.xor(f: F): X = x("xor", f)
fun X.xy(f: F): X = x("xy", f)
fun X.xyz(f: F): X = x("xyz", f)
fun X.y(f: F): X = x("y", f)
fun X.year(f: F): X = x("year", f)
fun X.yellow(f: F): X = x("yellow", f)
fun X.yes(f: F): X = x("yes", f)
fun X.z(f: F): X = x("z", f)
fun X.zero(f: F): X = x("zero", f)
fun X.zoom(f: F): X = x("zoom", f)

val X.a: X get() = a { this }
val X.above: X get() = above { this }
val X.abs: X get() = abs { this }
val X.absent: X get() = absent { this }
val X.absolute: X get() = absolute { this }
val X.abstract: X get() = abstract { this }
val X.abstraction: X get() = abstraction { this }
val X.accept: X get() = accept { this }
val X.access: X get() = access { this }
val X.accessible: X get() = accessible { this }
val X.acos: X get() = acos { this }
val X.activity: X get() = activity { this }
val X.actual: X get() = actual { this }
val X.add: X get() = add { this }
val X.addr: X get() = addr { this }
val X.address: X get() = address { this }
val X.admin: X get() = admin { this }
val X.after: X get() = after { this }
val X.age: X get() = age { this }
val X.all: X get() = all { this }
val X.alloc: X get() = alloc { this }
val X.allocate: X get() = allocate { this }
val X.alpha: X get() = alpha { this }
val X.always: X get() = always { this }
val X.am: X get() = am { this }
val X.amplitude: X get() = amplitude { this }
val X.anchor: X get() = anchor { this }
val X.and: X get() = and { this }
val X.angle: X get() = angle { this }
val X.anon: X get() = anon { this }
val X.antialias: X get() = antialias { this }
val X.antialiasing: X get() = antialiasing { this }
val X.anticlockwise: X get() = anticlockwise { this }
val X.any: X get() = any { this }
val X.anything: X get() = anything { this }
val X.appearance: X get() = appearance { this }
val X.append: X get() = append { this }
val X.appending: X get() = appending { this }
val X.application: X get() = application { this }
val X.applicative: X get() = applicative { this }
val X.applier: X get() = applier { this }
val X.apply: X get() = apply { this }
val X.arc: X get() = arc { this }
val X.area: X get() = area { this }
val X.arg: X get() = arg { this }
val X.argb: X get() = argb { this }
val X.args: X get() = args { this }
val X.argument: X get() = argument { this }
val X.arguments: X get() = arguments { this }
val X.arity: X get() = arity { this }
val X.arr: X get() = arr { this }
val X.array: X get() = array { this }
val X.arraycopy: X get() = arraycopy { this }
val X.arrow: X get() = arrow { this }
val X.as_: X get() = as_ { this }
val X.asin: X get() = asin { this }
val X.assert: X get() = assert { this }
val X.assignable: X get() = assignable { this }
val X.async: X get() = async { this }
val X.at: X get() = at { this }
val X.atan: X get() = atan { this }
val X.attention: X get() = attention { this }
val X.attr: X get() = attr { this }
val X.attribute: X get() = attribute { this }
val X.audio: X get() = audio { this }
val X.awt: X get() = awt { this }
val X.b: X get() = b { this }
val X.back: X get() = back { this }
val X.background: X get() = background { this }
val X.backslash: X get() = backslash { this }
val X.backtrace: X get() = backtrace { this }
val X.ball: X get() = ball { this }
val X.ban: X get() = ban { this }
val X.base: X get() = base { this }
val X.becomes: X get() = becomes { this }
val X.before: X get() = before { this }
val X.begin: X get() = begin { this }
val X.being: X get() = being { this }
val X.below: X get() = below { this }
val X.big: X get() = big { this }
val X.binary: X get() = binary { this }
val X.bind: X get() = bind { this }
val X.bindings: X get() = bindings { this }
val X.bit: X get() = bit { this }
val X.black: X get() = black { this }
val X.block: X get() = block { this }
val X.blue: X get() = blue { this }
val X.body: X get() = body { this }
val X.bool: X get() = bool { this }
val X.boolean: X get() = boolean { this }
val X.booleans: X get() = booleans { this }
val X.boost: X get() = boost { this }
val X.bottom: X get() = bottom { this }
val X.bounds: X get() = bounds { this }
val X.bold: X get() = bold { this }
val X.box: X get() = box { this }
val X.bpm: X get() = bpm { this }
val X.branch: X get() = branch { this }
val X.buf: X get() = buf { this }
val X.buffer: X get() = buffer { this }
val X.build: X get() = build { this }
val X.builder: X get() = builder { this }
val X.by: X get() = by { this }
val X.byte: X get() = byte { this }
val X.bytes: X get() = bytes { this }
val X.c: X get() = c { this }
val X.cache: X get() = cache { this }
val X.call: X get() = call { this }
val X.called: X get() = called { this }
val X.calling: X get() = calling { this }
val X.cancel: X get() = cancel { this }
val X.cancelable: X get() = cancelable { this }
val X.cancelled: X get() = cancelled { this }
val X.canvas: X get() = canvas { this }
val X.cap: X get() = cap { this }
val X.caps: X get() = caps { this }
val X.case: X get() = case { this }
val X.cast: X get() = cast { this }
val X.catching: X get() = catching { this }
val X.cause: X get() = cause { this }
val X.caution: X get() = caution { this }
val X.center: X get() = center { this }
val X.chain: X get() = chain { this }
val X.change: X get() = change { this }
val X.char: X get() = char { this }
val X.character: X get() = character { this }
val X.cheat: X get() = cheat { this }
val X.check: X get() = check { this }
val X.checked: X get() = checked { this }
val X.child: X get() = child { this }
val X.children: X get() = children { this }
val X.circle: X get() = circle { this }
val X.class_: X get() = class_ { this }
val X.classes: X get() = classes { this }
val X.clear: X get() = clear { this }
val X.click: X get() = click { this }
val X.clip: X get() = clip { this }
val X.clock: X get() = clock { this }
val X.clockwise: X get() = clockwise { this }
val X.clone: X get() = clone { this }
val X.clones: X get() = clones { this }
val X.close: X get() = close { this }
val X.closeable: X get() = closeable { this }
val X.closed: X get() = closed { this }
val X.closure: X get() = closure { this }
val X.code: X get() = code { this }
val X.codeblock: X get() = codeblock { this }
val X.codegen: X get() = codegen { this }
val X.collect: X get() = collect { this }
val X.collecting: X get() = collecting { this }
val X.color: X get() = color { this }
val X.colors: X get() = colors { this }
val X.column: X get() = column { this }
val X.columns: X get() = columns { this }
val X.com: X get() = com { this }
val X.comfort: X get() = comfort { this }
val X.comma: X get() = comma { this }
val X.command: X get() = command { this }
val X.comment: X get() = comment { this }
val X.common: X get() = common { this }
val X.compact: X get() = compact { this }
val X.compare: X get() = compare { this }
val X.compass: X get() = compass { this }
val X.component: X get() = component { this }
val X.components: X get() = components { this }
val X.compute: X get() = compute { this }
val X.concat: X get() = concat { this }
val X.condition: X get() = condition { this }
val X.conflicts: X get() = conflicts { this }
val X.connect: X get() = connect { this }
val X.connected: X get() = connected { this }
val X.connection: X get() = connection { this }
val X.connections: X get() = connections { this }
val X.console: X get() = console { this }
val X.const: X get() = const { this }
val X.constant: X get() = constant { this }
val X.constructor: X get() = constructor { this }
val X.constructors: X get() = constructors { this }
val X.constructs: X get() = constructs { this }
val X.constuctor: X get() = constuctor { this }
val X.consumer: X get() = consumer { this }
val X.consumers: X get() = consumers { this }
val X.contain: X get() = contain { this }
val X.contains: X get() = contains { this }
val X.content: X get() = content { this }
val X.context: X get() = context { this }
val X.continuous: X get() = continuous { this }
val X.control: X get() = control { this }
val X.convert: X get() = convert { this }
val X.coord: X get() = coord { this }
val X.coordinate: X get() = coordinate { this }
val X.coordinates: X get() = coordinates { this }
val X.coords: X get() = coords { this }
val X.copies: X get() = copies { this }
val X.copy: X get() = copy { this }
val X.cos: X get() = cos { this }
val X.cosh: X get() = cosh { this }
val X.count: X get() = count { this }
val X.counter: X get() = counter { this }
val X.cout: X get() = cout { this }
val X.cover: X get() = cover { this }
val X.crash: X get() = crash { this }
val X.create: X get() = create { this }
val X.created: X get() = created { this }
val X.ctor: X get() = ctor { this }
val X.current: X get() = current { this }
val X.curve: X get() = curve { this }
val X.cut: X get() = cut { this }
val X.cyan: X get() = cyan { this }
val X.d: X get() = d { this }
val X.dare: X get() = dare { this }
val X.dark: X get() = dark { this }
val X.data: X get() = data { this }
val X.database: X get() = database { this }
val X.day: X get() = day { this }
val X.debug: X get() = debug { this }
val X.declaration: X get() = declaration { this }
val X.declared: X get() = declared { this }
val X.declaring: X get() = declaring { this }
val X.decrement: X get() = decrement { this }
val X.deepnight: X get() = deepnight { this }
val X.def: X get() = def { this }
val X.default: X get() = default { this }
val X.define: X get() = define { this }
val X.degrees: X get() = degrees { this }
val X.delete: X get() = delete { this }
val X.demo: X get() = demo { this }
val X.depth: X get() = depth { this }
val X.derive: X get() = derive { this }
val X.describe: X get() = describe { this }
val X.destroy: X get() = destroy { this }
val X.detector: X get() = detector { this }
val X.dict: X get() = dict { this }
val X.dictionary: X get() = dictionary { this }
val X.did: X get() = did { this }
val X.difference: X get() = difference { this }
val X.digest: X get() = digest { this }
val X.dimensions: X get() = dimensions { this }
val X.direct: X get() = direct { this }
val X.display: X get() = display { this }
val X.div: X get() = div { this }
val X.divide: X get() = divide { this }
val X.divided: X get() = divided { this }
val X.divmod: X get() = divmod { this }
val X.do_: X get() = do_ { this }
val X.document: X get() = document { this }
val X.does: X get() = does { this }
val X.doing: X get() = doing { this }
val X.done: X get() = done { this }
val X.dot: X get() = dot { this }
val X.double: X get() = double { this }
val X.dp: X get() = dp { this }
val X.draw: X get() = draw { this }
val X.drawing: X get() = drawing { this }
val X.ds: X get() = ds { this }
val X.duty: X get() = duty { this }
val X.dynamic: X get() = dynamic { this }
val X.dynamics: X get() = dynamics { this }
val X.e: X get() = e { this }
val X.each: X get() = each { this }
val X.edge: X get() = edge { this }
val X.eight: X get() = eight { this }
val X.either: X get() = either { this }
val X.element: X get() = element { this }
val X.elements: X get() = elements { this }
val X.else_: X get() = else_ { this }
val X.email: X get() = email { this }
val X.empty: X get() = empty { this }
val X.end: X get() = end { this }
val X.ends: X get() = ends { this }
val X.enter: X get() = enter { this }
val X.entries: X get() = entries { this }
val X.entry: X get() = entry { this }
val X.enum: X get() = enum { this }
val X.enums: X get() = enums { this }
val X.eq: X get() = eq { this }
val X.equal: X get() = equal { this }
val X.equals_: X get() = equals_ { this }
val X.equatable: X get() = equatable { this }
val X.error: X get() = error { this }
val X.esc: X get() = esc { this }
val X.escape: X get() = escape { this }
val X.eval: X get() = eval { this }
val X.evaluate: X get() = evaluate { this }
val X.evaluated: X get() = evaluated { this }
val X.event: X get() = event { this }
val X.events: X get() = events { this }
val X.exactly: X get() = exactly { this }
val X.examples: X get() = examples { this }
val X.exception: X get() = exception { this }
val X.exceptions: X get() = exceptions { this }
val X.exclusive: X get() = exclusive { this }
val X.exec: X get() = exec { this }
val X.executable: X get() = executable { this }
val X.execute: X get() = execute { this }
val X.execution: X get() = execution { this }
val X.executor: X get() = executor { this }
val X.exists: X get() = exists { this }
val X.exit: X get() = exit { this }
val X.expand: X get() = expand { this }
val X.expanded: X get() = expanded { this }
val X.expands: X get() = expands { this }
val X.expected: X get() = expected { this }
val X.expression: X get() = expression { this }
val X.ext: X get() = ext { this }
val X.extends: X get() = extends { this }
val X.extractor: X get() = extractor { this }
val X.f: X get() = f { this }
val X.f32: X get() = f32 { this }
val X.f64: X get() = f64 { this }
val X.factory: X get() = factory { this }
val X.fading: X get() = fading { this }
val X.failed: X get() = failed { this }
val X.failures: X get() = failures { this }
val X.false_: X get() = false_ { this }
val X.family: X get() = family { this }
val X.fast: X get() = fast { this }
val X.father: X get() = father { this }
val X.female: X get() = female { this }
val X.fetch: X get() = fetch { this }
val X.fib: X get() = fib { this }
val X.field: X get() = field { this }
val X.fields: X get() = fields { this }
val X.file: X get() = file { this }
val X.files: X get() = files { this }
val X.fill: X get() = fill { this }
val X.filter: X get() = filter { this }
val X.final: X get() = final { this }
val X.finality: X get() = finality { this }
val X.finalizer: X get() = finalizer { this }
val X.find: X get() = find { this }
val X.finite: X get() = finite { this }
val X.first: X get() = first { this }
val X.five: X get() = five { this }
val X.flat: X get() = flat { this }
val X.flip: X get() = flip { this }
val X.float: X get() = float { this }
val X.float32: X get() = float32 { this }
val X.float64: X get() = float64 { this }
val X.floating: X get() = floating { this }
val X.flush: X get() = flush { this }
val X.fn: X get() = fn { this }
val X.fold: X get() = fold { this }
val X.folded: X get() = folded { this }
val X.folder: X get() = folder { this }
val X.font: X get() = font { this }
val X.footer: X get() = footer { this }
val X.for_: X get() = for_ { this }
val X.force: X get() = force { this }
val X.forced: X get() = forced { this }
val X.foreground: X get() = foreground { this }
val X.forget: X get() = forget { this }
val X.form: X get() = form { this }
val X.found: X get() = found { this }
val X.four: X get() = four { this }
val X.fragment: X get() = fragment { this }
val X.frame: X get() = frame { this }
val X.free: X get() = free { this }
val X.freeze: X get() = freeze { this }
val X.frequency: X get() = frequency { this }
val X.from: X get() = from { this }
val X.frozen: X get() = frozen { this }
val X.full: X get() = full { this }
val X.fully: X get() = fully { this }
val X.fun_: X get() = fun_ { this }
val X.func: X get() = func { this }
val X.function: X get() = function { this }
val X.functions: X get() = functions { this }
val X.functor: X get() = functor { this }
val X.future: X get() = future { this }
val X.futures: X get() = futures { this }
val X.g: X get() = g { this }
val X.game: X get() = game { this }
val X.gen: X get() = gen { this }
val X.generic: X get() = generic { this }
val X.generics: X get() = generics { this }
val X.get: X get() = get { this }
val X.gets: X get() = gets { this }
val X.getting: X get() = getting { this }
val X.give: X get() = give { this }
val X.given: X get() = given { this }
val X.gives: X get() = gives { this }
val X.global: X get() = global { this }
val X.glyph: X get() = glyph { this }
val X.google: X get() = google { this }
val X.gray: X get() = gray { this }
val X.green: X get() = green { this }
val X.grey: X get() = grey { this }
val X.grid: X get() = grid { this }
val X.h: X get() = h { this }
val X.h1: X get() = h1 { this }
val X.h2: X get() = h2 { this }
val X.h3: X get() = h3 { this }
val X.h4: X get() = h4 { this }
val X.h5: X get() = h5 { this }
val X.h6: X get() = h6 { this }
val X.hack: X get() = hack { this }
val X.hacker: X get() = hacker { this }
val X.handle: X get() = handle { this }
val X.has: X get() = has { this }
val X.hash: X get() = hash { this }
val X.hashes: X get() = hashes { this }
val X.haxe: X get() = haxe { this }
val X.head: X get() = head { this }
val X.header: X get() = header { this }
val X.heap: X get() = heap { this }
val X.height: X get() = height { this }
val X.heights: X get() = heights { this }
val X.hi: X get() = hi { this }
val X.high: X get() = high { this }
val X.hint: X get() = hint { this }
val X.holder: X get() = holder { this }
val X.horizontal: X get() = horizontal { this }
val X.horizontally: X get() = horizontally { this }
val X.host: X get() = host { this }
val X.hour: X get() = hour { this }
val X.href: X get() = href { this }
val X.html: X get() = html { this }
val X.http: X get() = http { this }
val X.husband: X get() = husband { this }
val X.hx: X get() = hx { this }
val X.i: X get() = i { this }
val X.icon: X get() = icon { this }
val X.identifier: X get() = identifier { this }
val X.identifiers: X get() = identifiers { this }
val X.if_: X get() = if_ { this }
val X.immediate: X get() = immediate { this }
val X.immutable: X get() = immutable { this }
val X.impl: X get() = impl { this }
val X.implement: X get() = implement { this }
val X.implements: X get() = implements { this }
val X.import: X get() = import { this }
val X.in_: X get() = in_ { this }
val X.inbpm: X get() = inbpm { this }
val X.increment: X get() = increment { this }
val X.indent: X get() = indent { this }
val X.index: X get() = index { this }
val X.infinite: X get() = infinite { this }
val X.info: X get() = info { this }
val X.inherit: X get() = inherit { this }
val X.init: X get() = init { this }
val X.initial: X get() = initial { this }
val X.initializer: X get() = initializer { this }
val X.inline: X get() = inline { this }
val X.input: X get() = input { this }
val X.insert: X get() = insert { this }
val X.instance: X get() = instance { this }
val X.instrument: X get() = instrument { this }
val X.instruments: X get() = instruments { this }
val X.i1: X get() = i1 { this }
val X.i2: X get() = i2 { this }
val X.i4: X get() = i4 { this }
val X.i8: X get() = i8 { this }
val X.i16: X get() = i16 { this }
val X.i32: X get() = i32 { this }
val X.i64: X get() = i64 { this }
val X.image: X get() = image { this }
val X.int: X get() = int { this }
val X.int16: X get() = int16 { this }
val X.int32: X get() = int32 { this }
val X.int64: X get() = int64 { this }
val X.int8: X get() = int8 { this }
val X.integer: X get() = integer { this }
val X.integers: X get() = integers { this }
val X.integral: X get() = integral { this }
val X.intent: X get() = intent { this }
val X.intercept: X get() = intercept { this }
val X.interface_: X get() = interface_ { this }
val X.intern: X get() = intern { this }
val X.interrupt: X get() = interrupt { this }
val X.inventory: X get() = inventory { this }
val X.invoke: X get() = invoke { this }
val X.ios: X get() = ios { this }
val X.ipad: X get() = ipad { this }
val X.iphone: X get() = iphone { this }
val X.is_: X get() = is_ { this }
val X.it: X get() = it { this }
val X.iterable: X get() = iterable { this }
val X.iterables: X get() = iterables { this }
val X.iteratively: X get() = iteratively { this }
val X.iterator: X get() = iterator { this }
val X.iterators: X get() = iterators { this }
val X.itself: X get() = itself { this }
val X.j: X get() = j { this }
val X.jam: X get() = jam { this }
val X.jar: X get() = jar { this }
val X.java: X get() = java { this }
val X.join: X get() = join { this }
val X.jump: X get() = jump { this }
val X.just: X get() = just { this }
val X.k: X get() = k { this }
val X.key: X get() = key { this }
val X.keyboard: X get() = keyboard { this }
val X.keyword: X get() = keyword { this }
val X.kick: X get() = kick { this }
val X.kotlin: X get() = kotlin { this }
val X.l: X get() = l { this }
val X.label: X get() = label { this }
val X.lambda: X get() = lambda { this }
val X.lang: X get() = lang { this }
val X.last: X get() = last { this }
val X.latch: X get() = latch { this }
val X.lazily: X get() = lazily { this }
val X.lazy_: X get() = lazy_ { this }
val X.left: X get() = left { this }
val X.len: X get() = len { this }
val X.length: X get() = length { this }
val X.lengths: X get() = lengths { this }
val X.leo: X get() = leo { this }
val X.leonardo: X get() = leonardo { this }
val X.leonize: X get() = leonize { this }
val X.leonized: X get() = leonized { this }
val X.leonizer: X get() = leonizer { this }
val X.lhs: X get() = lhs { this }
val X.lib: X get() = lib { this }
val X.library: X get() = library { this }
val X.light: X get() = light { this }
val X.line: X get() = line { this }
val X.lines: X get() = lines { this }
val X.linked: X get() = linked { this }
val X.list: X get() = list { this }
val X.listener: X get() = listener { this }
val X.lists: X get() = lists { this }
val X.literal: X get() = literal { this }
val X.lo: X get() = lo { this }
val X.load: X get() = load { this }
val X.loader: X get() = loader { this }
val X.lock: X get() = lock { this }
val X.log: X get() = log { this }
val X.login: X get() = login { this }
val X.logo: X get() = logo { this }
val X.logout: X get() = logout { this }
val X.lol: X get() = lol { this }
val X.long: X get() = long { this }
val X.look: X get() = look { this }
val X.lookup: X get() = lookup { this }
val X.loop: X get() = loop { this }
val X.lost: X get() = lost { this }
val X.low: X get() = low { this }
val X.lower: X get() = lower { this }
val X.ludum: X get() = ludum { this }
val X.ludumdare: X get() = ludumdare { this }
val X.m: X get() = m { this }
val X.mac: X get() = mac { this }
val X.macos: X get() = macos { this }
val X.macro: X get() = macro { this }
val X.magenta: X get() = magenta { this }
val X.mail: X get() = mail { this }
val X.main: X get() = main { this }
val X.make: X get() = make { this }
val X.male: X get() = male { this }
val X.manager: X get() = manager { this }
val X.map: X get() = map { this }
val X.mapping: X get() = mapping { this }
val X.maps: X get() = maps { this }
val X.mapt: X get() = mapt { this }
val X.margin: X get() = margin { this }
val X.marriage: X get() = marriage { this }
val X.match: X get() = match { this }
val X.matcher: X get() = matcher { this }
val X.matches: X get() = matches { this }
val X.matching: X get() = matching { this }
val X.max: X get() = max { this }
val X.maybe: X get() = maybe { this }
val X.measure: X get() = measure { this }
val X.melody: X get() = melody { this }
val X.mem: X get() = mem { this }
val X.member: X get() = member { this }
val X.members: X get() = members { this }
val X.membership: X get() = membership { this }
val X.memory: X get() = memory { this }
val X.merger: X get() = merger { this }
val X.message: X get() = message { this }
val X.meta: X get() = meta { this }
val X.method: X get() = method { this }
val X.methods: X get() = methods { this }
val X.metrics: X get() = metrics { this }
val X.micapolos: X get() = micapolos { this }
val X.middle: X get() = middle { this }
val X.millis: X get() = millis { this }
val X.min: X get() = min { this }
val X.minus: X get() = minus { this }
val X.minute: X get() = minute { this }
val X.miss: X get() = miss { this }
val X.missing: X get() = missing { this }
val X.mod: X get() = mod { this }
val X.mode: X get() = mode { this }
val X.modifier: X get() = modifier { this }
val X.modifiers: X get() = modifiers { this }
val X.module: X get() = module { this }
val X.monad: X get() = monad { this }
val X.month: X get() = month { this }
val X.more: X get() = more { this }
val X.mother: X get() = mother { this }
val X.motion: X get() = motion { this }
val X.mouse: X get() = mouse { this }
val X.move: X get() = move { this }
val X.mul: X get() = mul { this }
val X.multiply: X get() = multiply { this }
val X.mutable: X get() = mutable { this }
val X.my: X get() = my { this }
val X.n: X get() = n { this }
val X.name: X get() = name { this }
val X.named: X get() = named { this }
val X.names: X get() = names { this }
val X.nand: X get() = nand { this }
val X.native: X get() = native { this }
val X.negate: X get() = negate { this }
val X.new: X get() = new { this }
val X.newline: X get() = newline { this }
val X.next: X get() = next { this }
val X.night: X get() = night { this }
val X.nil: X get() = nil { this }
val X.nine: X get() = nine { this }
val X.no: X get() = no { this }
val X.node: X get() = node { this }
val X.non: X get() = non { this }
val X.none: X get() = none { this }
val X.nor: X get() = nor { this }
val X.not: X get() = not { this }
val X.note: X get() = note { this }
val X.notes: X get() = notes { this }
val X.nothing: X get() = nothing { this }
val X.now: X get() = now { this }
val X.null_: X get() = null_ { this }
val X.nullable: X get() = nullable { this }
val X.number: X get() = number { this }
val X.numbers: X get() = numbers { this }
val X.o: X get() = o { this }
val X.obj: X get() = obj { this }
val X.object_: X get() = object_ { this }
val X.objects: X get() = objects { this }
val X.of: X get() = of { this }
val X.off: X get() = off { this }
val X.office: X get() = office { this }
val X.offset: X get() = offset { this }
val X.ofib: X get() = ofib { this }
val X.on: X get() = on { this }
val X.one: X get() = one { this }
val X.only: X get() = only { this }
val X.op: X get() = op { this }
val X.open: X get() = open { this }
val X.operation: X get() = operation { this }
val X.operator: X get() = operator { this }
val X.option: X get() = option { this }
val X.optional: X get() = optional { this }
val X.optionals: X get() = optionals { this }
val X.or: X get() = or { this }
val X.orange: X get() = orange { this }
val X.order: X get() = order { this }
val X.ordinal: X get() = ordinal { this }
val X.org: X get() = org { this }
val X.original: X get() = original { this }
val X.otherwise: X get() = otherwise { this }
val X.out: X get() = out { this }
val X.outline: X get() = outline { this }
val X.output: X get() = output { this }
val X.oval: X get() = oval { this }
val X.over: X get() = over { this }
val X.overflow: X get() = overflow { this }
val X.owner: X get() = owner { this }
val X.p: X get() = p { this }
val X.package_: X get() = package_ { this }
val X.packages: X get() = packages { this }
val X.page: X get() = page { this }
val X.paint: X get() = paint { this }
val X.pair: X get() = pair { this }
val X.pane: X get() = pane { this }
val X.param: X get() = param { this }
val X.parameter: X get() = parameter { this }
val X.parameters: X get() = parameters { this }
val X.params: X get() = params { this }
val X.parent: X get() = parent { this }
val X.parentheses: X get() = parentheses { this }
val X.parse: X get() = parse { this }
val X.parser: X get() = parser { this }
val X.pass: X get() = pass { this }
val X.password: X get() = password { this }
val X.paste: X get() = paste { this }
val X.path: X get() = path { this }
val X.pattern: X get() = pattern { this }
val X.pause: X get() = pause { this }
val X.payload: X get() = payload { this }
val X.pc: X get() = pc { this }
val X.percent: X get() = percent { this }
val X.period: X get() = period { this }
val X.person: X get() = person { this }
val X.phase: X get() = phase { this }
val X.phone: X get() = phone { this }
val X.pi: X get() = pi { this }
val X.pin: X get() = pin { this }
val X.ping: X get() = ping { this }
val X.pink: X get() = pink { this }
val X.pins: X get() = pins { this }
val X.pixel: X get() = pixel { this }
val X.pkg: X get() = pkg { this }
val X.plain: X get() = plain { this }
val X.play: X get() = play { this }
val X.plus: X get() = plus { this }
val X.pm: X get() = pm { this }
val X.point: X get() = point { this }
val X.pong: X get() = pong { this }
val X.pop: X get() = pop { this }
val X.port: X get() = port { this }
val X.position: X get() = position { this }
val X.possible: X get() = possible { this }
val X.post: X get() = post { this }
val X.ppq: X get() = ppq { this }
val X.predecessor: X get() = predecessor { this }
val X.prefix: X get() = prefix { this }
val X.preprocess: X get() = preprocess { this }
val X.preprocessor: X get() = preprocessor { this }
val X.present: X get() = present { this }
val X.prev: X get() = prev { this }
val X.previous: X get() = previous { this }
val X.primitive: X get() = primitive { this }
val X.print: X get() = print { this }
val X.printed: X get() = printed { this }
val X.printer: X get() = printer { this }
val X.printing: X get() = printing { this }
val X.println: X get() = println { this }
val X.private: X get() = private { this }
val X.process: X get() = process { this }
val X.processed: X get() = processed { this }
val X.producer: X get() = producer { this }
val X.product: X get() = product { this }
val X.program: X get() = program { this }
val X.property: X get() = property { this }
val X.protected: X get() = protected { this }
val X.public: X get() = public { this }
val X.pull: X get() = pull { this }
val X.push: X get() = push { this }
val X.put: X get() = put { this }
val X.q: X get() = q { this }
val X.query: X get() = query { this }
val X.queue: X get() = queue { this }
val X.quicksort: X get() = quicksort { this }
val X.quote: X get() = quote { this }
val X.quoted: X get() = quoted { this }
val X.r: X get() = r { this }
val X.radians: X get() = radians { this }
val X.radius: X get() = radius { this }
val X.random: X get() = random { this }
val X.read: X get() = read { this }
val X.reader: X get() = reader { this }
val X.reading: X get() = reading { this }
val X.readonly: X get() = readonly { this }
val X.readutf: X get() = readutf { this }
val X.recover: X get() = recover { this }
val X.rect: X get() = rect { this }
val X.rectangle: X get() = rectangle { this }
val X.recurse: X get() = recurse { this }
val X.recursion: X get() = recursion { this }
val X.recursive: X get() = recursive { this }
val X.recursively: X get() = recursively { this }
val X.red: X get() = red { this }
val X.redirect: X get() = redirect { this }
val X.ref: X get() = ref { this }
val X.reference: X get() = reference { this }
val X.refl: X get() = refl { this }
val X.reflect: X get() = reflect { this }
val X.remainder: X get() = remainder { this }
val X.remove: X get() = remove { this }
val X.render: X get() = render { this }
val X.rendering: X get() = rendering { this }
val X.repeat: X get() = repeat { this }
val X.replace: X get() = replace { this }
val X.required: X get() = required { this }
val X.reset: X get() = reset { this }
val X.resolution: X get() = resolution { this }
val X.resolve: X get() = resolve { this }
val X.resolved: X get() = resolved { this }
val X.resolver: X get() = resolver { this }
val X.resource: X get() = resource { this }
val X.result: X get() = result { this }
val X.resume: X get() = resume { this }
val X.resumed: X get() = resumed { this }
val X.ret: X get() = ret { this }
val X.reti: X get() = reti { this }
val X.return_: X get() = return_ { this }
val X.returns: X get() = returns { this }
val X.reverse: X get() = reverse { this }
val X.rgb: X get() = rgb { this }
val X.rgba: X get() = rgba { this }
val X.rhs: X get() = rhs { this }
val X.right: X get() = right { this }
val X.root: X get() = root { this }
val X.rotate: X get() = rotate { this }
val X.round: X get() = round { this }
val X.row: X get() = row { this }
val X.rows: X get() = rows { this }
val X.rule: X get() = rule { this }
val X.run: X get() = run { this }
val X.running: X get() = running { this }
val X.runtime: X get() = runtime { this }
val X.s: X get() = s { this }
val X.save: X get() = save { this }
val X.sawtooth: X get() = sawtooth { this }
val X.say: X get() = say { this }
val X.scale: X get() = scale { this }
val X.scheme: X get() = scheme { this }
val X.scope: X get() = scope { this }
val X.scoped: X get() = scoped { this }
val X.scopes: X get() = scopes { this }
val X.screen: X get() = screen { this }
val X.script: X get() = script { this }
val X.search: X get() = search { this }
val X.second: X get() = second { this }
val X.select: X get() = select { this }
val X.self: X get() = self { this }
val X.semicolon: X get() = semicolon { this }
val X.sentinel: X get() = sentinel { this }
val X.separated: X get() = separated { this }
val X.separator: X get() = separator { this }
val X.sequence: X get() = sequence { this }
val X.sequencer: X get() = sequencer { this }
val X.serial: X get() = serial { this }
val X.server: X get() = server { this }
val X.set: X get() = set { this }
val X.sets: X get() = sets { this }
val X.seven: X get() = seven { this }
val X.sex: X get() = sex { this }
val X.shape: X get() = shape { this }
val X.shapes: X get() = shapes { this }
val X.shift: X get() = shift { this }
val X.short: X get() = short { this }
val X.shortquote: X get() = shortquote { this }
val X.show: X get() = show { this }
val X.shutdown: X get() = shutdown { this }
val X.side: X get() = side { this }
val X.simple: X get() = simple { this }
val X.sin: X get() = sin { this }
val X.sine: X get() = sine { this }
val X.single: X get() = single { this }
val X.singleton: X get() = singleton { this }
val X.singly: X get() = singly { this }
val X.sinh: X get() = sinh { this }
val X.sink: X get() = sink { this }
val X.sinks: X get() = sinks { this }
val X.six: X get() = six { this }
val X.size: X get() = size { this }
val X.skip: X get() = skip { this }
val X.slash: X get() = slash { this }
val X.sleep: X get() = sleep { this }
val X.slice: X get() = slice { this }
val X.sliding: X get() = sliding { this }
val X.slow: X get() = slow { this }
val X.some: X get() = some { this }
val X.sort: X get() = sort { this }
val X.source: X get() = source { this }
val X.space: X get() = space { this }
val X.span: X get() = span { this }
val X.spanning: X get() = spanning { this }
val X.splice: X get() = splice { this }
val X.split: X get() = split { this }
val X.spouse: X get() = spouse { this }
val X.square: X get() = square { this }
val X.squared: X get() = squared { this }
val X.sr: X get() = sr { this }
val X.src: X get() = src { this }
val X.stack: X get() = stack { this }
val X.stacks: X get() = stacks { this }
val X.stand: X get() = stand { this }
val X.start: X get() = start { this }
val X.started: X get() = started { this }
val X.starts: X get() = starts { this }
val X.state: X get() = state { this }
val X.statement: X get() = statement { this }
val X.statements: X get() = statements { this }
val X.static: X get() = static { this }
val X.std: X get() = std { this }
val X.step: X get() = step { this }
val X.stop: X get() = stop { this }
val X.stream: X get() = stream { this }
val X.string: X get() = string { this }
val X.strings: X get() = strings { this }
val X.stroke: X get() = stroke { this }
val X.struct: X get() = struct { this }
val X.style: X get() = style { this }
val X.sub: X get() = sub { this }
val X.subject: X get() = subject { this }
val X.submit: X get() = submit { this }
val X.subpackages: X get() = subpackages { this }
val X.substr: X get() = substr { this }
val X.substring: X get() = substring { this }
val X.subtract: X get() = subtract { this }
val X.successor: X get() = successor { this }
val X.suffix: X get() = suffix { this }
val X.sum: X get() = sum { this }
val X.super_: X get() = super_ { this }
val X.superclass: X get() = superclass { this }
val X.supervisor: X get() = supervisor { this }
val X.supplier: X get() = supplier { this }
val X.suppliers: X get() = suppliers { this }
val X.suppressed: X get() = suppressed { this }
val X.switch: X get() = switch { this }
val X.symbol: X get() = symbol { this }
val X.symbols: X get() = symbols { this }
val X.syntax: X get() = syntax { this }
val X.system: X get() = system { this }
val X.t: X get() = t { this }
val X.tab: X get() = tab { this }
val X.tag: X get() = tag { this }
val X.tail: X get() = tail { this }
val X.tan: X get() = tan { this }
val X.tanh: X get() = tanh { this }
val X.tap: X get() = tap { this }
val X.target: X get() = target { this }
val X.temp: X get() = temp { this }
val X.template: X get() = template { this }
val X.tempo: X get() = tempo { this }
val X.tempos: X get() = tempos { this }
val X.ten: X get() = ten { this }
val X.term: X get() = term { this }
val X.terms: X get() = terms { this }
val X.test: X get() = test { this }
val X.testing: X get() = testing { this }
val X.tests: X get() = tests { this }
val X.text: X get() = text { this }
val X.that: X get() = that { this }
val X.the: X get() = the { this }
val X.then_: X get() = then_ { this }
val X.these: X get() = these { this }
val X.third: X get() = third { this }
val X.this_: X get() = this_ { this }
val X.thread: X get() = thread { this }
val X.three: X get() = three { this }
val X.throw_: X get() = throw_ { this }
val X.throwable: X get() = throwable { this }
val X.throws: X get() = throws { this }
val X.thunk: X get() = thunk { this }
val X.time: X get() = time { this }
val X.timeout: X get() = timeout { this }
val X.times: X get() = times { this }
val X.timestamp: X get() = timestamp { this }
val X.to: X get() = to { this }
val X.top: X get() = top { this }
val X.touch: X get() = touch { this }
val X.trace: X get() = trace { this }
val X.traced: X get() = traced { this }
val X.track: X get() = track { this }
val X.transform: X get() = transform { this }
val X.translate: X get() = translate { this }
val X.triangle: X get() = triangle { this }
val X.trigger: X get() = trigger { this }
val X.true_: X get() = true_ { this }
val X.truth: X get() = truth { this }
val X.tuple: X get() = tuple { this }
val X.two: X get() = two { this }
val X.type: X get() = type { this }
val X.types: X get() = types { this }
val X.u: X get() = u { this }
val X.uint: X get() = uint { this }
val X.uint16: X get() = uint16 { this }
val X.uint32: X get() = uint32 { this }
val X.uint64: X get() = uint64 { this }
val X.uint8: X get() = uint8 { this }
val X.unchecked: X get() = unchecked { this }
val X.undefined: X get() = undefined { this }
val X.underscorify: X get() = underscorify { this }
val X.undo: X get() = undo { this }
val X.unhandled: X get() = unhandled { this }
val X.unindent: X get() = unindent { this }
val X.unit: X get() = unit { this }
val X.unknown: X get() = unknown { this }
val X.unmodifiable: X get() = unmodifiable { this }
val X.unquote: X get() = unquote { this }
val X.unquoted: X get() = unquoted { this }
val X.unread: X get() = unread { this }
val X.unresolved: X get() = unresolved { this }
val X.unsafe: X get() = unsafe { this }
val X.unsafes: X get() = unsafes { this }
val X.unshift: X get() = unshift { this }
val X.unsigned: X get() = unsigned { this }
val X.update: X get() = update { this }
val X.upper: X get() = upper { this }
val X.uri: X get() = uri { this }
val X.url: X get() = url { this }
val X.use: X get() = use { this }
val X.user: X get() = user { this }
val X.util: X get() = util { this }
val X.v: X get() = v { this }
val X.val_: X get() = val_ { this }
val X.value: X get() = value { this }
val X.values: X get() = values { this }
val X.var_: X get() = var_ { this }
val X.variable: X get() = variable { this }
val X.variables: X get() = variables { this }
val X.vec: X get() = vec { this }
val X.vec2: X get() = vec2 { this }
val X.vec3: X get() = vec3 { this }
val X.vec4: X get() = vec4 { this }
val X.vector: X get() = vector { this }
val X.versionuid: X get() = versionuid { this }
val X.vertical: X get() = vertical { this }
val X.vertically: X get() = vertically { this }
val X.view: X get() = view { this }
val X.violet: X get() = violet { this }
val X.visibility: X get() = visibility { this }
val X.visible: X get() = visible { this }
val X.visit: X get() = visit { this }
val X.visitor: X get() = visitor { this }
val X.void: X get() = void { this }
val X.volume: X get() = volume { this }
val X.w: X get() = w { this }
val X.wait: X get() = wait { this }
val X.warn: X get() = warn { this }
val X.warning: X get() = warning { this }
val X.watch: X get() = watch { this }
val X.wave: X get() = wave { this }
val X.weak: X get() = weak { this }
val X.week: X get() = week { this }
val X.while_: X get() = while_ { this }
val X.white: X get() = white { this }
val X.widget: X get() = widget { this }
val X.width: X get() = width { this }
val X.wife: X get() = wife { this }
val X.win: X get() = win { this }
val X.winding: X get() = winding { this }
val X.window: X get() = window { this }
val X.wire: X get() = wire { this }
val X.with: X get() = with { this }
val X.without: X get() = without { this }
val X.word: X get() = word { this }
val X.wrap: X get() = wrap { this }
val X.write: X get() = write { this }
val X.writes: X get() = writes { this }
val X.writing: X get() = writing { this }
val X.x: X get() = x { this }
val X.xfib: X get() = xfib { this }
val X.xor: X get() = xor { this }
val X.xy: X get() = xy { this }
val X.xyz: X get() = xyz { this }
val X.y: X get() = y { this }
val X.year: X get() = year { this }
val X.yellow: X get() = yellow { this }
val X.yes: X get() = yes { this }
val X.z: X get() = z { this }
val X.zero: X get() = zero { this }
val X.zoom: X get() = zoom { this }