package leo13.untyped

const val applyName = "apply"
const val bindName = "bind"
const val bindingsName = "bindings"
const val boundName = "bound"
const val caseName = "case"
const val choiceName = "choice"
const val constantName = "constant"
const val contextName = "context"
const val eitherName = "either"
const val emptyName = "empty"
const val expressionName = "expression"
const val functionName = "function"
const val getName = "get"
const val lineName = "line"
const val noneName = "none"
const val parentName = "parent"
const val previousName = "previous"
const val setName = "set"
const val switchName = "switch"