package leo25.natives

val argsName = "args"
val arrayName = "array"
val className = "class"
val elementName = "element"
val falseName = "false"
val fieldName = "field"
val getName = "get"
val invokeName = "invoke"
val integerName = "integer"
val javaName = "java"
val methodName = "method"
val nameName = "name"
val nullName = "null"
val lengthName = "length"
val objectName = "object"
val trueName = "true"
val typesName = "types"